import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

// MARK: - Localization Helper
struct ReportLocalization {
    let isChinese: Bool
    
    init() {
        self.isChinese = LocalizationManager.shared.currentLanguage == .chinese
    }
    
    var progressReport: String { isChinese ? "学员进度报告" : "PROGRESS REPORT" }
    var sessions: String { isChinese ? "课时" : "SESSIONS" }
    var rating: String { isChinese ? "评分" : "RATING" }
    var coach: String { isChinese ? "教练" : "COACH" }
    var outOf10: String { isChinese ? "满分10" : "out of 10" }
    var yourCoach: String { isChinese ? "您的教练" : "Your coach" }
    var noContract: String { isChinese ? "无合同" : "No contract" }
    var remaining: String { isChinese ? "剩余" : "left" }
    var skills: String { isChinese ? "技能评估" : "SKILLS" }
    var highlights: String { isChinese ? "亮点" : "HIGHLIGHTS" }
    var topSkill: String { isChinese ? "最强技能" : "Top Skill" }
    var overall: String { isChinese ? "综合评分" : "Overall" }
    var coachNote: String { isChinese ? "教练评语" : "Coach Note" }
    var membership: String { isChinese ? "会员信息" : "MEMBERSHIP" }
    var memberSince: String { isChinese ? "入会时间" : "Member Since" }
    var attendanceRate: String { isChinese ? "出勤率" : "Attendance" }
    var contractExpires: String { isChinese ? "合同到期" : "Expires" }
    var improvement: String { isChinese ? "待提升" : "Improve" }
    var personalizedFor: String { isChinese ? "专属报告" : "Personalized for" }
    var years: String { isChinese ? "岁" : "yrs" }
    var shareWithParent: String { isChinese ? "分享给家长" : "Share with Parent" }
    var autoGenerated: String { isChinese ? "此报告根据学员数据自动生成" : "This report is auto-generated from your student's data" }
    var parentReport: String { isChinese ? "家长报告" : "Parent Report" }
    var close: String { isChinese ? "关闭" : "Close" }
    
    func skillLabel(_ index: Int) -> String {
        let en = ["Shooting", "Defense", "Ball\nHandling", "IQ", "Athletic", "Teamwork", "Coach"]
        let cn = ["投篮", "防守", "控球", "球商", "体能", "团队", "态度"]
        return isChinese ? cn[index] : en[index]
    }
    
    func skillName(_ name: String) -> String {
        let map: [String: String] = [
            "Shooting": "投篮", "Defense": "防守", "Ball Handling": "控球",
            "Basketball IQ": "球商", "Athleticism": "体能", "Teamwork": "团队", "Coachability": "态度"
        ]
        return isChinese ? (map[name] ?? name) : name
    }
    
    // Performance radar labels (6-axis hybrid)
    func performanceLabel(_ index: Int) -> String {
        let en = ["Scoring", "Playmaking", "Rebounding", "Defense", "Athletic", "Effort"]
        let cn = ["得分", "组织", "篮板", "防守", "体能", "投入"]
        return isChinese ? cn[index] : en[index]
    }
    
    // Stat grid labels (Chinese parents understand these better)
    var ppgLabel: String { isChinese ? "得分" : "PPG" }
    var apgLabel: String { isChinese ? "助攻" : "APG" }
    var rpgLabel: String { isChinese ? "篮板" : "RPG" }
    var stlLabel: String { isChinese ? "抢断" : "STL" }
    var blkLabel: String { isChinese ? "盖帽" : "BLK" }
    var effLabel: String { isChinese ? "效率" : "EFF" }
    
    // Handedness labels
    func handednessLabel(_ handedness: Handedness) -> String {
        guard isChinese else { return handedness.shortName }
        switch handedness {
        case .right: return "右"
        case .left: return "左"
        case .ambidextrous: return "双"
        }
    }
    
    var noGameData: String { isChinese ? "暂无比赛数据" : "No game data yet" }
    var basedOnGames: String { isChinese ? "基于场比赛" : "Based on games" }
    var comparedToPeers: String { isChinese ? "• 对比同班学员" : "• vs program peers" }
}

// MARK: - Program Stats Context (for peer comparison)
struct ProgramStatsContext {
    let maxPPG: Double
    let maxRPG: Double
    let maxAPG: Double
    let maxSPG: Double
    let maxBPG: Double
    let maxEffort: Double
    let avgPPG: Double
    let studentCount: Int
    
    static let empty = ProgramStatsContext(maxPPG: 15, maxRPG: 8, maxAPG: 5, maxSPG: 3, maxBPG: 2, maxEffort: 7, avgPPG: 0, studentCount: 0)
    
    /// Calculate program stats from all enrolled students' training stats
    static func calculate(from allStats: [TrainingSessionStats]) -> ProgramStatsContext {
        let validStats = allStats.filter { $0.hasStats }
        guard !validStats.isEmpty else { return .empty }

        func effort(_ s: TrainingSessionStats) -> Double {
            // Tangible overall involvement per game.
            // Using per-game rates keeps this fair across different total games.
            s.rpg + s.apg + s.spg + s.bpg
        }
        
        let maxPPG = max(validStats.map { $0.ppg }.max() ?? 15, 5) // Minimum 5 to avoid division issues
        let maxRPG = max(validStats.map { $0.rpg }.max() ?? 8, 3)
        let maxAPG = max(validStats.map { $0.apg }.max() ?? 5, 2)
        let maxSPG = max(validStats.map { $0.spg }.max() ?? 3, 1)
        let maxBPG = max(validStats.map { $0.bpg }.max() ?? 2, 1)
        let maxEffort = max(validStats.map { effort($0) }.max() ?? 7, 2)
        let avgPPG = validStats.map { $0.ppg }.reduce(0, +) / Double(validStats.count)
        
        return ProgramStatsContext(
            maxPPG: maxPPG,
            maxRPG: maxRPG,
            maxAPG: maxAPG,
            maxSPG: maxSPG,
            maxBPG: maxBPG,
            maxEffort: maxEffort,
            avgPPG: avgPPG,
            studentCount: validStats.count
        )
    }
}

// MARK: - Smart Blending Engine for Performance Radar
/// Blends tangible game stats with coach evaluations using confidence-based weighting.
/// More games played = higher weight on stats. Stats always prioritized over subjective evaluation.
struct PerformanceRadarMetrics {
    let scoring: Double      // PPG blended with coach scoring eval
    let playmaking: Double   // APG blended with coach playmaking eval
    let rebounding: Double   // RPG blended with coach rebounding eval
    let defense: Double      // (SPG+BPG)/2 blended with coach defense eval
    let athleticism: Double  // Pure coach evaluation (no stat)
    let effort: Double       // Tangible (RPG+APG+SPG+BPG) normalized vs peers
    let hasGameData: Bool
    let gamesPlayed: Int
    let isComparedToPeers: Bool
    
    // MARK: - Confidence-Based Stat Weights
    /// Returns the weight for game stats based on games played (0.0 - 0.8)
    /// More games = more confidence in stats = higher weight
    private static func statWeight(gamesPlayed: Int) -> Double {
        switch gamesPlayed {
        case 0:      return 0.0   // No games: 100% coach eval
        case 1...2:  return 0.5   // Few games: 50/50 blend
        case 3...5:  return 0.6   // Some games: 60% stats
        case 6...10: return 0.7   // Good sample: 70% stats
        default:     return 0.8   // Large sample: 80% stats (max)
        }
    }
    
    /// Compute hybrid metrics from game stats and coach evaluations (legacy)
    static func compute(from stats: TrainingSessionStats?, skills: SkillsEvaluation) -> PerformanceRadarMetrics {
        return compute(from: stats, skills: skills, programContext: nil)
    }
    
    /// Smart blending engine: combines game stats with coach evaluations
    /// - Stats are normalized against program peers (or fixed ceiling if no peers)
    /// - Weight shifts toward stats as more games are played
    /// - Athleticism is coach evaluation (no measurable stat)
    static func compute(from stats: TrainingSessionStats?, skills: SkillsEvaluation, programContext: ProgramStatsContext?) -> PerformanceRadarMetrics {
        let hasData = stats?.hasStats ?? false
        let gp = stats?.gamesPlayed ?? 0
        let context = programContext ?? .empty
        let hasPeerData = context.studentCount >= 1
        
        // Calculate confidence-based weight
        let statW = statWeight(gamesPlayed: gp)
        let evalW = 1.0 - statW
        
        // Helper: normalize a stat against max (peer or fixed ceiling)
        func normalize(_ value: Double, peerMax: Double, fixedMax: Double) -> Double {
            let max = (hasPeerData && peerMax > 0) ? peerMax : fixedMax
            return min((value / max) * 10.0, 10.0)
        }
        
        // Helper: blend stat with coach evaluation
        // Adds a floor so blended value never drops below 40% of coach eval
        // This prevents 0-stat scenarios from completely negating coach evaluation
        func blend(stat: Double, eval: Int) -> Double {
            let raw = stat * statW + Double(eval) * evalW
            let floor = Double(eval) * 0.4  // Minimum 40% of coach eval
            return max(raw, floor)
        }
        
        // SCORING: PPG (ceiling: peer max or 15 PPG)
        let scoringStat = hasData ? normalize(stats!.ppg, peerMax: context.maxPPG, fixedMax: 15.0) : 0
        let scoring = hasData ? blend(stat: scoringStat, eval: skills.scoring) : Double(skills.scoring)
        
        // PLAYMAKING: APG (ceiling: peer max or 5 APG)
        let playmakingStat = hasData ? normalize(stats!.apg, peerMax: context.maxAPG, fixedMax: 5.0) : 0
        let playmaking = hasData ? blend(stat: playmakingStat, eval: skills.playmaking) : Double(skills.playmaking)
        
        // REBOUNDING: RPG (ceiling: peer max or 8 RPG)
        let reboundingStat = hasData ? normalize(stats!.rpg, peerMax: context.maxRPG, fixedMax: 8.0) : 0
        let rebounding = hasData ? blend(stat: reboundingStat, eval: skills.rebounding) : Double(skills.rebounding)
        
        // DEFENSE: (SPG + BPG) / 2 (ceiling: peer max or 3 SPG / 2 BPG)
        let spgNorm = hasData ? normalize(stats!.spg, peerMax: context.maxSPG, fixedMax: 3.0) : 0
        let bpgNorm = hasData ? normalize(stats!.bpg, peerMax: context.maxBPG, fixedMax: 2.0) : 0
        let defenseStat = (spgNorm + bpgNorm) / 2.0
        // Defense uses slightly lower stat weight (0.6 max) since steals/blocks don't capture full defense
        let defenseStatW = min(statW, 0.6)
        let defenseEvalW = 1.0 - defenseStatW
        let defense = hasData ? (defenseStat * defenseStatW + Double(skills.defense) * defenseEvalW) : Double(skills.defense)
        
        // ATHLETICISM: Pure coach evaluation (no measurable stat)
        let athleticism = Double(skills.athleticism)

        // EFFORT: tangible overall involvement (rebounds + assists + steals + blocks per game)
        // Kept stat-only to remain measurable and comparable.
        let effortRaw = hasData ? (stats!.rpg + stats!.apg + stats!.spg + stats!.bpg) : 0
        let effortStat = hasData ? normalize(effortRaw, peerMax: context.maxEffort, fixedMax: 7.0) : 0
        let effort = hasData ? effortStat : Double((skills.rebounding + skills.playmaking + skills.defense) / 3)
        
        return PerformanceRadarMetrics(
            scoring: scoring,
            playmaking: playmaking,
            rebounding: rebounding,
            defense: defense,
            athleticism: athleticism,
            effort: effort,
            hasGameData: hasData,
            gamesPlayed: gp,
            isComparedToPeers: hasPeerData && hasData
        )
    }
    
    /// Returns normalized values (0-1) for radar chart display
    var normalizedValues: [Double] {
        [scoring, playmaking, rebounding, defense, athleticism, effort].map { $0 / 10.0 }
    }
    
    /// Returns a breakdown of how each axis was computed (for debugging/transparency)
    var blendDescription: String {
        let w = Self.statWeight(gamesPlayed: gamesPlayed)
        if !hasGameData {
            return "100% Coach Evaluation"
        }
        return "Stats: \(Int(w * 100))% | Eval: \(Int((1-w) * 100))% (\(gamesPlayed) games)"
    }
}

// MARK: - Performance Radar Chart View (6-axis hybrid)
struct PerformanceRadarChartView: View {
    let metrics: PerformanceRadarMetrics
    let accentColor: Color
    let loc: ReportLocalization
    var isLightMode: Bool = false
    
    private let axisCount = 6
    private var labels: [String] { (0..<axisCount).map { loc.performanceLabel($0) } }
    private var values: [Double] { metrics.normalizedValues }
    
    // Dynamic colors for light/dark mode
    private var gridColor: Color { isLightMode ? Color(hex: "#CCCCCC") : AppTheme.textTertiary }
    private var labelColor: Color { isLightMode ? Color(hex: "#333333") : AppTheme.textPrimary }
    private var indicatorColor: Color { isLightMode ? Color(hex: "#666666") : .green }
    
    var body: some View {
        GeometryReader { geo in
            let center = CGPoint(x: geo.size.width / 2, y: (geo.size.height - 20) / 2)
            let radius = min(geo.size.width, geo.size.height - 20) / 2 - 40
            
            ZStack {
                // Grid rings
                ForEach([0.25, 0.5, 0.75, 1.0], id: \.self) { s in
                    radarPath(Array(repeating: s, count: axisCount), center, radius)
                        .stroke(gridColor.opacity(0.3), lineWidth: 1)
                }
                // Axes
                ForEach(0..<axisCount, id: \.self) { i in
                    Path { p in
                        p.move(to: center)
                        p.addLine(to: point(center, radius, angle(i)))
                    }.stroke(gridColor.opacity(0.4), lineWidth: 1)
                }
                // Data fill
                radarPath(values, center, radius)
                    .fill(accentColor.opacity(0.3))
                radarPath(values, center, radius)
                    .stroke(accentColor, lineWidth: 2)
                // Points
                ForEach(0..<axisCount, id: \.self) { i in
                    Circle().fill(accentColor).frame(width: 6, height: 6)
                        .position(point(center, radius * values[i], angle(i)))
                }
                // Labels
                ForEach(0..<axisCount, id: \.self) { i in
                    Text(labels[i])
                        .font(.system(size: 9, weight: .semibold))
                        .foregroundColor(labelColor)
                        .multilineTextAlignment(.center)
                        .frame(width: 55)
                        .position(point(center, radius + 22, angle(i)))
                }
            }
            
            // Data source indicator at absolute bottom
            VStack {
                Spacer()
                HStack(spacing: 4) {
                    Spacer()
                    if metrics.hasGameData {
                        Text("\(metrics.gamesPlayed) \(loc.basedOnGames)")
                            .font(.system(size: 7, weight: .medium))
                            .foregroundColor(indicatorColor.opacity(0.8))
                        if metrics.isComparedToPeers {
                            Text(loc.comparedToPeers)
                                .font(.system(size: 7, weight: .medium))
                                .foregroundColor(.cyan.opacity(0.8))
                        }
                    } else {
                        Text(loc.noGameData)
                            .font(.system(size: 7, weight: .medium))
                            .foregroundColor(gridColor)
                    }
                    Spacer()
                }
            }
        }
    }
    
    private func angle(_ i: Int) -> Double { -.pi/2 + (2 * .pi * Double(i) / Double(axisCount)) }
    private func point(_ c: CGPoint, _ r: CGFloat, _ a: Double) -> CGPoint {
        CGPoint(x: c.x + r * Foundation.cos(a), y: c.y + r * Foundation.sin(a))
    }
    private func radarPath(_ vals: [Double], _ c: CGPoint, _ r: CGFloat) -> Path {
        Path { p in
            for (i, v) in vals.enumerated() {
                let pt = point(c, r * v, angle(i))
                i == 0 ? p.move(to: pt) : p.addLine(to: pt)
            }
            p.closeSubpath()
        }
    }
}

// MARK: - Legacy Radar Chart View (7-axis coach evaluation only)
/// Legacy 6-axis radar chart (uses coach evaluation only, for parent sharing)
struct RadarChartView: View {
    let skills: SkillsEvaluation
    let accentColor: Color
    let loc: ReportLocalization
    
    private let axisCount = 6
    private var labels: [String] { (0..<6).map { loc.performanceLabel($0) } }
    
    private var values: [Double] {
        skills.radarValues.map { $0 / 10.0 }
    }
    
    var body: some View {
        GeometryReader { geo in
            let center = CGPoint(x: geo.size.width / 2, y: geo.size.height / 2)
            let radius = min(geo.size.width, geo.size.height) / 2 - 35
            
            ZStack {
                // Grid
                ForEach([0.25, 0.5, 0.75, 1.0], id: \.self) { s in
                    radarPath(Array(repeating: s, count: axisCount), center, radius)
                        .stroke(AppTheme.textTertiary.opacity(0.3), lineWidth: 1)
                }
                // Axes
                ForEach(0..<axisCount, id: \.self) { i in
                    Path { p in
                        p.move(to: center)
                        p.addLine(to: point(center, radius, angle(i)))
                    }.stroke(AppTheme.textTertiary.opacity(0.4), lineWidth: 1)
                }
                // Data fill
                radarPath(values, center, radius)
                    .fill(accentColor.opacity(0.3))
                radarPath(values, center, radius)
                    .stroke(accentColor, lineWidth: 2)
                // Points
                ForEach(0..<axisCount, id: \.self) { i in
                    Circle().fill(accentColor).frame(width: 6, height: 6)
                        .position(point(center, radius * values[i], angle(i)))
                }
                // Labels
                ForEach(0..<axisCount, id: \.self) { i in
                    Text(labels[i])
                        .font(.system(size: 8, weight: .medium))
                        .foregroundColor(AppTheme.textPrimary)
                        .multilineTextAlignment(.center)
                        .frame(width: 50)
                        .position(point(center, radius + 22, angle(i)))
                }
            }
        }
    }
    
    private func angle(_ i: Int) -> Double { -.pi/2 + (2 * .pi * Double(i) / Double(axisCount)) }
    private func point(_ c: CGPoint, _ r: CGFloat, _ a: Double) -> CGPoint {
        CGPoint(x: c.x + r * Foundation.cos(a), y: c.y + r * Foundation.sin(a))
    }
    private func radarPath(_ vals: [Double], _ c: CGPoint, _ r: CGFloat) -> Path {
        Path { p in
            for (i, v) in vals.enumerated() {
                let pt = point(c, r * v, angle(i))
                i == 0 ? p.move(to: pt) : p.addLine(to: pt)
            }
            p.closeSubpath()
        }
    }
}

// MARK: - Parent Report View (Redesigned - Card-Based)
struct StudentParentReportView: View {
    let student: Student
    let player: Player?
    let contract: Contract?
    let programName: String?
    let coachName: String
    let orgName: String
    var trainingStats: TrainingSessionStats?
    var programContext: ProgramStatsContext? = nil
#if os(iOS)
    let profileImage: UIImage?
#else
    let profileImage: NSImage?
#endif
    var isLightMode: Bool = false
    
    private let loc = ReportLocalization()
    private var skills: SkillsEvaluation { player?.skills ?? SkillsEvaluation() }
    private var accent: Color { Color.avatarColor(student.avatarColor) }
    
    // Clean, modern color palette
    private var bgPrimary: Color { isLightMode ? Color(hex: "#F8F9FA") : Color(hex: "#0A0A0A") }
    private var bgCard: Color { isLightMode ? .white : Color(hex: "#1A1A1A") }
    private var textPrimary: Color { isLightMode ? Color(hex: "#1A1A1A") : .white }
    private var textSecondary: Color { isLightMode ? Color(hex: "#6B7280") : .white.opacity(0.7) }
    private var textTertiary: Color { isLightMode ? Color(hex: "#9CA3AF") : .white.opacity(0.4) }
    private var cardShadow: Color { isLightMode ? .black.opacity(0.06) : .clear }
    
    var body: some View {
        ZStack {
            bgPrimary
            
            // Watermark using actual app icon
            Image("HoopwiseLogo")
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: 120, height: 120)
                .opacity(0.06)
                .offset(y: 180)
            
            VStack(spacing: 12) {
                // Baseball Card (Header + Stats with trend arrows)
                baseballCard
                
                // Contract Status Card (compact)
                contractStatusCard
                
                // Footer branding
                footerBranding
            }
            .padding(12)
        }
        .frame(width: 380, height: 570) // iPhone photo aspect ~4:3
    }
    
    // MARK: - Baseball Card (Matching Intelligence Profile Layout)
    
    // Deterministic background image URL based on student ID
    private var backgroundImageURL: String {
        StudentProfileHeaderView.basketballURL(for: student.id)
    }
    
    private let cardBackground = Color(hex: "#F5F0E6")
    private let cardBorder = Color(hex: "#8B7355")
    private let statLabelColor = Color(hex: "#666666")
    
    private var baseballCard: some View {
        VStack(spacing: 0) {
            // MARK: Top Section (Blurred background with name)
            topSection
            
            // MARK: Middle Section (Profile photo overlapping + info)
            middleSection
            
            // MARK: Season Label
            seasonLabel
            
            // MARK: Stats Grid
            statsGridCard
        }
        .background(cardBackground)
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .overlay(
            RoundedRectangle(cornerRadius: 12)
                .stroke(cardBorder, lineWidth: 4)
        )
        .shadow(color: .black.opacity(0.3), radius: 8, x: 0, y: 4)
    }
    
    private var topSection: some View {
        ZStack {
            // Background image with blur
            AsyncImage(url: URL(string: backgroundImageURL)) { phase in
                switch phase {
                case .success(let image):
                    image
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .blur(radius: 4)
                case .failure(_), .empty:
                    Color.gray.opacity(0.3)
                @unknown default:
                    Color.gray.opacity(0.3)
                }
            }
            .frame(height: 140)
            .clipped()
            .overlay(
                LinearGradient(
                    colors: [.black.opacity(0.5), .black.opacity(0.2)],
                    startPoint: .top, endPoint: .bottom
                )
            )
            
            // Name overlay - Chinese name bigger when in Chinese mode
            VStack(spacing: 4) {
                if loc.isChinese, let chinese = student.chineseName {
                    // Chinese mode: Chinese name is primary (bigger)
                    Text(chinese)
                        .font(.system(size: 22, weight: .heavy))
                        .foregroundColor(.white)
                    Text(student.name.uppercased())
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(.white.opacity(0.8))
                        .tracking(1)
                } else if let chinese = student.chineseName {
                    // English mode: English name is primary (bigger)
                    Text(chinese)
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(.white.opacity(0.9))
                    Text(student.name.uppercased())
                        .font(.system(size: 20, weight: .heavy))
                        .foregroundColor(.white)
                        .tracking(1)
                        .multilineTextAlignment(.center)
                        .lineLimit(2)
                        .minimumScaleFactor(0.8)
                } else {
                    // No Chinese name - just show English
                    Text(student.name.uppercased())
                        .font(.system(size: 20, weight: .heavy))
                        .foregroundColor(.white)
                        .tracking(1)
                        .multilineTextAlignment(.center)
                        .lineLimit(2)
                        .minimumScaleFactor(0.8)
                }
            }
            .frame(maxWidth: .infinity)
            .padding(.horizontal, 50)
            .padding(.top, 16)
            
            // Jersey number (top right)
            if let jerseyNumber = player?.jerseyNumber {
                VStack {
                    HStack {
                        Spacer()
                        ZStack {
                            Circle().stroke(.white, lineWidth: 2).frame(width: 40, height: 40)
                            Text("\(jerseyNumber)").font(.system(size: 18, weight: .bold)).foregroundColor(.white)
                        }
                        .padding(.trailing, 12).padding(.top, 12)
                    }
                    Spacer()
                }
            }
        }
        .frame(height: 140)
    }
    
    private var middleSection: some View {
        ZStack {
            // Profile photo (overlapping top section)
            profilePhotoView
                .offset(y: -35)
            
            // Side elements
            HStack(alignment: .bottom, spacing: 0) {
                // Position badge (left)
                positionBadgeView
                    .frame(width: 70, alignment: .leading)
                    .padding(.leading, 12)
                
                Spacer()
                
                // Basic stats (right)
                basicStatsView
                    .frame(width: 70, alignment: .trailing)
                    .padding(.trailing, 12)
            }
        }
        .padding(.top, 6)
        .padding(.bottom, 4)
    }
    
    private var profilePhotoView: some View {
        ZStack {
            Circle().fill(.white).frame(width: 86, height: 86)
            Circle().stroke(cardBorder, lineWidth: 3).frame(width: 80, height: 80)
            
            if let img = profileImage {
                #if os(iOS)
                Image(uiImage: img).resizable().aspectRatio(contentMode: .fill).frame(width: 74, height: 74).clipShape(Circle())
                #else
                Image(nsImage: img).resizable().aspectRatio(contentMode: .fill).frame(width: 74, height: 74).clipShape(Circle())
                #endif
            } else {
                Circle().fill(accent).frame(width: 74, height: 74)
                Text(student.initials).font(.system(size: 24, weight: .bold, design: .rounded)).foregroundColor(.white)
            }
        }
    }
    
    private var positionBadgeView: some View {
        ZStack {
            Rectangle().fill(.white).frame(width: 44, height: 44).rotationEffect(.degrees(45))
                .overlay(Rectangle().stroke(Color.gray.opacity(0.3), lineWidth: 1).rotationEffect(.degrees(45)))
            Text(player?.position ?? "—").font(.system(size: 16, weight: .bold)).foregroundColor(.black)
        }
        .frame(width: 54, height: 54)
    }
    
    private var basicStatsView: some View {
        VStack(alignment: .trailing, spacing: 3) {
            statRowView(label: loc.isChinese ? "年龄" : "AGE", value: student.age != nil ? "\(student.age!)" : "—")
            statRowView(label: loc.isChinese ? "身高" : "HT", value: heightString)
            statRowView(label: loc.isChinese ? "手" : "HAND", value: handednessString)
        }
    }
    
    private var handednessString: String {
        guard let handedness = player?.handedness else { return "—" }
        return loc.handednessLabel(handedness)
    }
    
    private func statRowView(label: String, value: String) -> some View {
        HStack(spacing: 4) {
            Text(label).font(.system(size: 9, weight: .medium)).foregroundColor(statLabelColor)
            Text(value).font(.system(size: 12, weight: .bold)).foregroundColor(.black)
        }
    }
    
    private var heightString: String {
        guard let height = player?.heightCm else { return "—" }
        let feet = Int(height / 30.48)
        let inches = Int((height / 2.54).truncatingRemainder(dividingBy: 12))
        return "\(feet)'\(inches)\""
    }
    
    private var seasonLabel: some View {
        Text(loc.isChinese ? "自 \(memberSinceYear)" : "SINCE \(memberSinceYear)")
            .font(.system(size: 11, weight: .bold))
            .foregroundColor(.white)
            .padding(.horizontal, 16)
            .padding(.vertical, 5)
            .background(Capsule().fill(Color.blue))
            .padding(.vertical, 6)
    }
    
    private var statsGridCard: some View {
        VStack(spacing: 0) {
            Rectangle().fill(Color.gray.opacity(0.3)).frame(height: 1)
            HStack(spacing: 0) {
                statCellWithTrend(value: trainingStats?.ppg ?? 0, label: loc.ppgLabel, trend: .stable)
                Rectangle().fill(Color.gray.opacity(0.3)).frame(width: 1)
                statCellWithTrend(value: trainingStats?.apg ?? 0, label: loc.apgLabel, trend: .stable)
                Rectangle().fill(Color.gray.opacity(0.3)).frame(width: 1)
                statCellWithTrend(value: trainingStats?.rpg ?? 0, label: loc.rpgLabel, trend: .stable)
            }.frame(height: 55)
            Rectangle().fill(Color.gray.opacity(0.3)).frame(height: 1)
            HStack(spacing: 0) {
                statCellWithTrend(value: trainingStats?.spg ?? 0, label: loc.stlLabel, trend: .stable)
                Rectangle().fill(Color.gray.opacity(0.3)).frame(width: 1)
                statCellWithTrend(value: trainingStats?.bpg ?? 0, label: loc.blkLabel, trend: .stable)
                Rectangle().fill(Color.gray.opacity(0.3)).frame(width: 1)
                statCellWithTrend(value: efficiency, label: loc.effLabel, trend: .stable)
            }.frame(height: 55)
        }
    }
    
    private enum StatTrend {
        case up, down, stable
        
        var icon: String {
            switch self {
            case .up: return "arrow.up"
            case .down: return "arrow.down"
            case .stable: return "minus"
            }
        }
        
        var color: Color {
            switch self {
            case .up: return .green
            case .down: return .red
            case .stable: return .gray.opacity(0.4)
            }
        }
    }
    
    private func statCellWithTrend(value: Double, label: String, trend: StatTrend) -> some View {
        VStack(spacing: 2) {
            HStack(spacing: 3) {
                Text(String(format: "%.1f", value))
                    .font(.system(size: 24, weight: .bold, design: .rounded))
                    .foregroundColor(.black)
                Image(systemName: trend.icon)
                    .font(.system(size: 8, weight: .bold))
                    .foregroundColor(trend.color)
            }
            Text(label)
                .font(.system(size: 10, weight: .medium))
                .foregroundColor(statLabelColor)
        }
        .frame(maxWidth: .infinity)
    }
    
    private var memberSinceYear: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy"
        return formatter.string(from: student.createdAt)
    }
    
    private func formatHeight(_ cm: Double) -> String {
        let totalInches = cm / 2.54
        let feet = Int(totalInches / 12)
        let inches = Int(totalInches.truncatingRemainder(dividingBy: 12))
        return "\(feet)'\(inches)\""
    }
    
    // MARK: - Stats Grid (Cream Section)
    
    private var statsGridSection: some View {
        let creamBg = isLightMode ? Color(hex: "#F5F0E6") : Color(hex: "#2A2520")
        let statColor = isLightMode ? Color(hex: "#1A1A1A") : Color.white
        let labelColor = isLightMode ? Color(hex: "#666666") : Color.white.opacity(0.6)
        
        return VStack(spacing: 0) {
            // Top row: PPG, APG, RPG
            HStack(spacing: 0) {
                statGridItem(String(format: "%.1f", trainingStats?.ppg ?? 0), "PPG", statColor, labelColor)
                Divider().frame(height: 50).background(labelColor.opacity(0.3))
                statGridItem(String(format: "%.1f", trainingStats?.apg ?? 0), "APG", statColor, labelColor)
                Divider().frame(height: 50).background(labelColor.opacity(0.3))
                statGridItem(String(format: "%.1f", trainingStats?.rpg ?? 0), "RPG", statColor, labelColor)
            }
            
            Divider().background(labelColor.opacity(0.3))
            
            // Bottom row: STL, BLK, EFF
            HStack(spacing: 0) {
                statGridItem(String(format: "%.1f", trainingStats?.spg ?? 0), "STL", statColor, labelColor)
                Divider().frame(height: 50).background(labelColor.opacity(0.3))
                statGridItem(String(format: "%.1f", trainingStats?.bpg ?? 0), "BLK", statColor, labelColor)
                Divider().frame(height: 50).background(labelColor.opacity(0.3))
                statGridItem(String(format: "%.1f", efficiency), "EFF", statColor, labelColor)
            }
        }
        .padding(.vertical, 12)
        .background(creamBg)
    }
    
    private var efficiency: Double {
        guard let stats = trainingStats else { return 0 }
        return stats.ppg + stats.rpg + stats.apg + stats.spg + stats.bpg
    }
    
    private func statGridItem(_ value: String, _ label: String, _ valueColor: Color, _ labelColor: Color) -> some View {
        VStack(spacing: 4) {
            Text(value).font(.system(size: 32, weight: .bold, design: .rounded)).foregroundColor(valueColor)
            Text(label).font(.system(size: 12, weight: .semibold)).foregroundColor(labelColor)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 8)
    }
    
    // MARK: - Contract Status Card (Compact)
    
    private var contractStatusCard: some View {
        HStack(spacing: 0) {
            // Type badge + Attended
            VStack(spacing: 2) {
                if let c = contract {
                    Text(loc.isChinese ? c.typeLabelChinese : c.typeLabel)
                        .font(.system(size: 9, weight: .bold)).foregroundColor(.white)
                        .padding(.horizontal, 6).padding(.vertical, 2)
                        .background(Color.indigo).cornerRadius(4)
                }
                Text("\(contract?.sessionCount ?? 0)")
                    .font(.system(size: 22, weight: .bold, design: .rounded)).foregroundColor(.green)
                Text(loc.isChinese ? "已参加" : "Attended").font(.system(size: 9)).foregroundColor(textSecondary)
            }.frame(maxWidth: .infinity)
            
            Rectangle().fill(textTertiary.opacity(0.2)).frame(width: 1, height: 40)
            
            // Enrolled date
            VStack(spacing: 2) {
                Image(systemName: "calendar").font(.system(size: 10)).foregroundColor(.blue)
                Text(contract?.enrollmentDate.formatted(.dateTime.month(.abbreviated).day()) ?? "—")
                    .font(.system(size: 14, weight: .bold, design: .rounded)).foregroundColor(.blue)
                Text(loc.isChinese ? "入学" : "Enrolled").font(.system(size: 9)).foregroundColor(textSecondary)
            }.frame(maxWidth: .infinity)
            
            Rectangle().fill(textTertiary.opacity(0.2)).frame(width: 1, height: 40)
            
            // Weeks
            VStack(spacing: 2) {
                Image(systemName: "clock").font(.system(size: 10)).foregroundColor(.purple)
                Text("\(weeksEnrolled)")
                    .font(.system(size: 22, weight: .bold, design: .rounded)).foregroundColor(.purple)
                Text(loc.isChinese ? "周" : "Weeks").font(.system(size: 9)).foregroundColor(textSecondary)
            }.frame(maxWidth: .infinity)
        }
        .padding(.vertical, 10)
        .padding(.horizontal, 8)
        .background(bgCard)
        .cornerRadius(12)
    }
    
    private var weeksEnrolled: Int {
        guard let c = contract else { return 0 }
        return Calendar.current.dateComponents([.weekOfYear], from: c.enrollmentDate, to: Date()).weekOfYear ?? 0
    }
    
    // MARK: - Stat Trends Card
    
    private var statTrendsCard: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(loc.isChinese ? "数据趋势" : "STAT TRENDS")
                .font(.system(size: 10, weight: .bold)).foregroundColor(textTertiary).tracking(1)
            
            // Trends grid - 2 rows of 3
            VStack(spacing: 6) {
                HStack(spacing: 8) {
                    trendItem("PPG", trainingStats?.ppg ?? 0, trendDirection(for: "ppg"), .orange)
                    trendItem("APG", trainingStats?.apg ?? 0, trendDirection(for: "apg"), .blue)
                    trendItem("RPG", trainingStats?.rpg ?? 0, trendDirection(for: "rpg"), .green)
                }
                HStack(spacing: 8) {
                    trendItem("STL", trainingStats?.spg ?? 0, trendDirection(for: "spg"), .red)
                    trendItem("BLK", trainingStats?.bpg ?? 0, trendDirection(for: "bpg"), .purple)
                    trendItem("EFF", efficiency, trendDirection(for: "eff"), accent)
                }
            }
        }
        .padding(12)
        .background(bgCard)
        .cornerRadius(12)
    }
    
    private func trendItem(_ label: String, _ value: Double, _ trend: TrendDirection, _ color: Color) -> some View {
        HStack(spacing: 4) {
            VStack(alignment: .leading, spacing: 1) {
                Text(label).font(.system(size: 9, weight: .medium)).foregroundColor(textTertiary)
                Text(String(format: "%.1f", value))
                    .font(.system(size: 16, weight: .bold, design: .rounded)).foregroundColor(color)
            }
            Spacer()
            Image(systemName: trend.icon)
                .font(.system(size: 10, weight: .bold))
                .foregroundColor(trend.color)
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 6)
        .background(color.opacity(0.1))
        .cornerRadius(8)
    }
    
    private enum TrendDirection {
        case up, down, stable
        var icon: String {
            switch self {
            case .up: return "arrow.up.right"
            case .down: return "arrow.down.right"
            case .stable: return "minus"
            }
        }
        var color: Color {
            switch self {
            case .up: return .green
            case .down: return .red
            case .stable: return .gray
            }
        }
    }
    
    private func trendDirection(for stat: String) -> TrendDirection {
        // Simplified trend calculation - compare recent vs overall
        // In production, this would compare last N sessions vs previous N
        guard let stats = trainingStats, stats.gamesPlayed > 2 else { return .stable }
        // For now, return stable as placeholder - actual trend logic would need historical data
        return .stable
    }
    
    private var highlightsCard: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(loc.highlights).font(.system(size: 11, weight: .bold)).foregroundColor(textTertiary).tracking(1)
            highlightItem("trophy.fill", .yellow, loc.topSkill, loc.skillName(topSkillName))
            if let stats = trainingStats, stats.hasStats {
                highlightItem("chart.bar.fill", accent, loc.isChinese ? "场均数据" : "Averages", "\(String(format: "%.1f", stats.ppg)) PPG • \(String(format: "%.1f", stats.rpg)) RPG")
            }
            if let notes = player?.coachNotes, !notes.isEmpty {
                highlightItem("quote.bubble.fill", .purple, loc.coachNote, String(notes.prefix(50)) + (notes.count > 50 ? "..." : ""))
            }
        }
        .padding(16)
        .background(bgCard)
        .cornerRadius(16)
        .shadow(color: cardShadow, radius: 6, y: 3)
    }
    
    private func highlightItem(_ icon: String, _ color: Color, _ title: String, _ value: String) -> some View {
        HStack(spacing: 12) {
            Image(systemName: icon).font(.system(size: 14)).foregroundColor(color).frame(width: 28, height: 28).background(color.opacity(0.15)).cornerRadius(8)
            VStack(alignment: .leading, spacing: 2) {
                Text(title).font(.system(size: 10, weight: .medium)).foregroundColor(textTertiary)
                Text(value).font(.system(size: 13, weight: .semibold)).foregroundColor(textPrimary).lineLimit(1)
            }
            Spacer()
        }
    }
    
    private var personalizedName: String {
        if let chinese = student.chineseName, !chinese.isEmpty {
            return chinese
        }
        return student.name.components(separatedBy: " ").first ?? student.name
    }
    
    private var footerBranding: some View {
        VStack(spacing: 6) {
            // Centered app logo (blue tint)
            Image("HoopwiseLogo")
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: 28, height: 28)
                .colorMultiply(Color.blue)
            
            // Bottom row: personalization and date
            HStack {
                HStack(spacing: 4) {
                    Image(systemName: "checkmark.seal.fill").font(.system(size: 10)).foregroundColor(.green)
                    Text("\(loc.personalizedFor) \(personalizedName)")
                        .font(.system(size: 9)).foregroundColor(textSecondary)
                }
                
                Spacer()
                
                Text(formattedDate).font(.system(size: 9)).foregroundColor(textTertiary)
            }
        }
        .padding(.top, 8)
    }
    
    // MARK: - Legacy (kept for compatibility)
    private var headerSection: some View {
        VStack(spacing: 12) {
            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text(orgName.uppercased())
                        .font(.system(size: 9, weight: .bold)).tracking(1)
                        .foregroundColor(textTertiary)
                    Text(loc.progressReport)
                        .font(.system(size: 10, weight: .bold)).tracking(0.8)
                        .foregroundColor(accent)
                }
                Spacer()
                Text(formattedDate)
                    .font(.system(size: 10, weight: .medium))
                    .foregroundColor(textTertiary)
            }
            HStack(spacing: 14) {
                // Profile picture with actual image support
                ZStack {
                    Circle()
                        .fill(LinearGradient(colors: [accent, accent.opacity(0.6)], startPoint: .topLeading, endPoint: .bottomTrailing))
                        .frame(width: 72, height: 72)
                    
                    if let img = profileImage {
                        #if os(iOS)
                        Image(uiImage: img)
                            .resizable()
                            .aspectRatio(contentMode: .fill)
                            .frame(width: 68, height: 68)
                            .clipShape(Circle())
                        #else
                        Image(nsImage: img)
                            .resizable()
                            .aspectRatio(contentMode: .fill)
                            .frame(width: 68, height: 68)
                            .clipShape(Circle())
                        #endif
                    } else {
                        Text(student.initials)
                            .font(.system(size: 24, weight: .bold, design: .rounded))
                            .foregroundColor(.white)
                    }
                }
                .shadow(color: accent.opacity(0.4), radius: 8, x: 0, y: 4)
                
                VStack(alignment: .leading, spacing: 3) {
                    Text(student.name)
                        .font(.system(size: 20, weight: .bold, design: .rounded))
                        .foregroundColor(textPrimary)
                    if let cn = student.chineseName {
                        Text(cn).font(.system(size: 13)).foregroundColor(textSecondary)
                    }
                    HStack(spacing: 6) {
                        if let age = student.age {
                            Text("\(age) \(loc.years)").font(.system(size: 10, weight: .medium))
                                .foregroundColor(textTertiary)
                        }
                        if let prog = programName {
                            Text("•").foregroundColor(textTertiary)
                            Text(prog).font(.system(size: 10, weight: .medium)).foregroundColor(accent)
                        }
                    }
                }
                Spacer()
            }
        }
        .padding(16)
        .background(LinearGradient(colors: [bgCard, bgPrimary], startPoint: .top, endPoint: .bottom))
    }
    
    private var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.locale = Locale(identifier: loc.isChinese ? "zh_CN" : "en_US")
        return formatter.string(from: Date())
    }
    
    private var statsRow: some View {
        HStack(spacing: 8) {
            statCard(loc.sessions, contract.map { "\($0.attendedSessions)/\($0.totalSessions)" } ?? "—",
                     contract.map { "\($0.remainingSessions) \(loc.remaining)" } ?? loc.noContract, "figure.basketball",
                     (contract?.remainingSessions ?? 0) <= 3 ? Color(hex: "#FF4757") : Color(hex: "#00D26A"))
            statCard(loc.coach, coachName.components(separatedBy: " ").first ?? "—", loc.yourCoach, "person.fill", accent)
        }
    }
    
    private var membershipSection: some View {
        HStack(spacing: 8) {
            miniStatCard(loc.memberSince, formattedMemberDate, "calendar.badge.clock", Color(hex: "#5B8DEF"))
            miniStatCard(loc.attendanceRate, attendanceRateString, "chart.bar.fill", attendanceColor)
            if let expiry = contract?.expiryDate {
                miniStatCard(loc.contractExpires, formattedExpiry(expiry), "clock.badge.exclamationmark", expiryColor(expiry))
            } else {
                miniStatCard(loc.improvement, weakestSkill, "arrow.up.circle.fill", Color(hex: "#FF6B35"))
            }
        }
    }
    
    private var formattedMemberDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = loc.isChinese ? "yyyy年M月" : "MMM yyyy"
        return formatter.string(from: student.createdAt)
    }
    
    private var attendanceRateString: String {
        guard let c = contract, c.totalSessions > 0 else { return "—" }
        let rate = Double(c.attendedSessions) / Double(c.totalSessions) * 100
        return "\(Int(rate))%"
    }
    
    private var attendanceColor: Color {
        guard let c = contract, c.totalSessions > 0 else { return Color(hex: "#95A5A6") }
        let rate = Double(c.attendedSessions) / Double(c.totalSessions)
        if rate >= 0.8 { return Color(hex: "#00D26A") }
        if rate >= 0.6 { return Color(hex: "#FFB800") }
        return Color(hex: "#FF4757")
    }
    
    private func formattedExpiry(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = loc.isChinese ? "M月d日" : "MMM d"
        return formatter.string(from: date)
    }
    
    private func expiryColor(_ date: Date) -> Color {
        let daysLeft = Calendar.current.dateComponents([.day], from: Date(), to: date).day ?? 0
        if daysLeft <= 7 { return Color(hex: "#FF4757") }
        if daysLeft <= 30 { return Color(hex: "#FFB800") }
        return Color(hex: "#00D26A")
    }
    
    private var weakestSkill: String {
        let skillValues = [
            ("Scoring", skills.scoring), ("Playmaking", skills.playmaking), ("Rebounding", skills.rebounding),
            ("Defense", skills.defense), ("Athleticism", skills.athleticism), ("Intangibles", skills.intangibles)
        ]
        let weakest = skillValues.min(by: { $0.1 < $1.1 })?.0 ?? "—"
        return loc.skillName(weakest)
    }
    
    private func statCard(_ title: String, _ value: String, _ sub: String, _ icon: String, _ color: Color) -> some View {
        VStack(spacing: 5) {
            Image(systemName: icon).font(.system(size: 15)).foregroundColor(color)
            Text(title).font(.system(size: 7, weight: .bold)).foregroundColor(textTertiary).tracking(0.5)
            Text(value).font(.system(size: 15, weight: .bold, design: .rounded)).foregroundColor(textPrimary).lineLimit(1).minimumScaleFactor(0.7)
            Text(sub).font(.system(size: 7)).foregroundColor(textTertiary)
        }
        .frame(maxWidth: .infinity).padding(.vertical, 10)
        .background(bgCard).cornerRadius(10)
    }
    
    private func miniStatCard(_ title: String, _ value: String, _ icon: String, _ color: Color) -> some View {
        HStack(spacing: 6) {
            Image(systemName: icon).font(.system(size: 12)).foregroundColor(color)
            VStack(alignment: .leading, spacing: 1) {
                Text(title).font(.system(size: 7, weight: .medium)).foregroundColor(textTertiary)
                Text(value).font(.system(size: 10, weight: .bold)).foregroundColor(textPrimary).lineLimit(1)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(8)
        .background(bgCard).cornerRadius(8)
    }
    
    private var trainingStatsSection: some View {
        Group {
            if let stats = trainingStats, stats.hasStats {
                VStack(alignment: .leading, spacing: 8) {
                    Text(loc.isChinese ? "训练数据" : "TRAINING STATS")
                        .font(.system(size: 8, weight: .bold))
                        .foregroundColor(textTertiary)
                        .tracking(0.8)
                    
                    HStack(spacing: 6) {
                        trainingStatCard("PPG", String(format: "%.1f", stats.ppg), Color(hex: "#FF9500"))
                        trainingStatCard("RPG", String(format: "%.1f", stats.rpg), Color(hex: "#5B8DEF"))
                        trainingStatCard("APG", String(format: "%.1f", stats.apg), Color(hex: "#00D26A"))
                        trainingStatCard("SPG", String(format: "%.1f", stats.spg), Color(hex: "#AF52DE"))
                        trainingStatCard("BPG", String(format: "%.1f", stats.bpg), Color(hex: "#FF3B30"))
                        trainingStatCard(loc.isChinese ? "场" : "GP", "\(stats.gamesPlayed)", accent)
                    }
                }
                .padding(12)
                .background(bgCard)
                .cornerRadius(12)
            }
        }
    }
    
    private func trainingStatCard(_ label: String, _ value: String, _ color: Color) -> some View {
        VStack(spacing: 3) {
            Text(value)
                .font(.system(size: 16, weight: .bold, design: .rounded))
                .foregroundColor(color)
            Text(label)
                .font(.system(size: 8, weight: .semibold))
                .foregroundColor(textTertiary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 8)
        .background(color.opacity(0.15))
        .cornerRadius(8)
    }
    
    private var performanceMetrics: PerformanceRadarMetrics {
        PerformanceRadarMetrics.compute(from: trainingStats, skills: skills, programContext: programContext)
    }
    
    private var skillsSection: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(loc.isChinese ? "表现分析" : "PERFORMANCE").font(.system(size: 8, weight: .bold)).foregroundColor(textTertiary).tracking(0.8)
            PerformanceRadarChartView(metrics: performanceMetrics, accentColor: accent, loc: loc, isLightMode: isLightMode).frame(height: 160)
        }
        .padding(12).background(bgCard).cornerRadius(12)
    }
    
    private var highlightsSection: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(loc.highlights).font(.system(size: 8, weight: .bold)).foregroundColor(textTertiary).tracking(0.8)
            highlightRow("trophy.fill", Color(hex: "#FFB800"), loc.topSkill, loc.skillName(topSkillName))
            if let stats = trainingStats, stats.hasStats {
                let value = "\(String(format: "%.1f", stats.ppg)) PPG • \(String(format: "%.1f", stats.rpg)) RPG • \(String(format: "%.1f", stats.apg)) APG"
                highlightRow("chart.bar.fill", accent, loc.isChinese ? "比赛表现" : "Game Performance", value)
            }
            if let focus = focusAreaName {
                highlightRow("target", Color(hex: "#00C2FF"), loc.improvement, loc.skillName(focus))
            }
            if let notes = player?.coachNotes, !notes.isEmpty {
                highlightRow("quote.bubble.fill", accent, loc.coachNote, String(notes.prefix(45)) + (notes.count > 45 ? "..." : ""))
            }
        }
        .padding(12).background(bgCard).cornerRadius(12)
    }
    
    private func highlightRow(_ icon: String, _ color: Color, _ title: String, _ value: String) -> some View {
        HStack(spacing: 8) {
            Image(systemName: icon).font(.system(size: 11)).foregroundColor(color)
                .frame(width: 22, height: 22).background(color.opacity(0.2)).cornerRadius(5)
            VStack(alignment: .leading, spacing: 0) {
                Text(title).font(.system(size: 8)).foregroundColor(textTertiary)
                Text(value).font(.system(size: 11, weight: .semibold)).foregroundColor(textPrimary).lineLimit(1)
            }
            Spacer()
        }
    }
    
    private var topSkillName: String {
        // Top-skill label is derived from the same 6 axes shown in the radar.
        // (Last axis is tangible Effort, so we approximate it via playmaking/rebounding/defense evaluation.)
        [("Scoring", skills.scoring), ("Playmaking", skills.playmaking), ("Rebounding", skills.rebounding),
         ("Defense", skills.defense), ("Athleticism", skills.athleticism), ("Effort", (skills.playmaking + skills.rebounding + skills.defense) / 3)]
            .max(by: { $0.1 < $1.1 })?.0 ?? "—"
    }

    private var focusAreaName: String? {
        let axes: [(String, Double)] = [
            ("Scoring", performanceMetrics.scoring),
            ("Playmaking", performanceMetrics.playmaking),
            ("Rebounding", performanceMetrics.rebounding),
            ("Defense", performanceMetrics.defense),
            ("Athleticism", performanceMetrics.athleticism),
            ("Effort", performanceMetrics.effort)
        ]
        return axes.min(by: { $0.1 < $1.1 })?.0
    }
    
    private var footerSection: some View {
        HStack {
            Image(systemName: "checkmark.seal.fill").font(.system(size: 11)).foregroundColor(accent)
            Text("\(loc.personalizedFor) \(student.name.components(separatedBy: " ").first ?? student.name)")
                .font(.system(size: 9)).foregroundColor(textTertiary)
            Spacer()
            Text("Hoopwise").font(.system(size: 10, weight: .bold, design: .rounded)).foregroundColor(accent)
        }
        .padding(.top, 6)
    }
}

// MARK: - Image Generator
#if canImport(UIKit)
@MainActor
struct StudentReportImageGenerator {
    static func generateImage(student: Student, player: Player?, contract: Contract?,
                              programName: String?, coachName: String, orgName: String,
                              trainingStats: TrainingSessionStats?,
                              programContext: ProgramStatsContext? = nil,
                              profileImage: UIImage?,
                              isLightMode: Bool = false) -> UIImage? {
        let view = StudentParentReportView(student: student, player: player, contract: contract,
                                           programName: programName, coachName: coachName,
                                           orgName: orgName, trainingStats: trainingStats,
                                           programContext: programContext,
                                           profileImage: profileImage,
                                           isLightMode: isLightMode)
        let controller = UIHostingController(rootView: view)
        controller.view.backgroundColor = .clear
        
        // Measure the natural content size
        let targetWidth: CGFloat = 380
        let fittingSize = controller.view.systemLayoutSizeFitting(
            CGSize(width: targetWidth, height: UIView.layoutFittingCompressedSize.height),
            withHorizontalFittingPriority: .required,
            verticalFittingPriority: .fittingSizeLevel
        )
        let size = CGSize(width: targetWidth, height: max(fittingSize.height, 700))
        controller.view.bounds = CGRect(origin: .zero, size: size)
        controller.view.layoutIfNeeded()
        
        let renderer = UIGraphicsImageRenderer(size: size)
        return renderer.image { _ in
            controller.view.drawHierarchy(in: controller.view.bounds, afterScreenUpdates: true)
        }
    }
}
#endif

// MARK: - Parent Report Sheet
struct ParentReportSheet: View {
    @Environment(\.dismiss) var dismiss
    @EnvironmentObject var dataManager: DataManager
    @Environment(\.horizontalSizeClass) private var horizontalSizeClass
    let student: Student
    let player: Player?
    let contract: Contract?
    let programName: String?
    let coachName: String
    
    private let loc = ReportLocalization()
    
    // Cached training stats to avoid recalculating on every render
    @State private var cachedTrainingStats: TrainingSessionStats?
    @State private var isLightMode = false
    
#if os(iOS)
    @State private var generatedImage: UIImage?
    @State private var profileImage: UIImage?
#else
    @State private var generatedImage: NSImage?
    @State private var profileImage: NSImage?
#endif
    @State private var isGenerating = false
    @State private var showShareSheet = false
    
    private var trainingStats: TrainingSessionStats? {
        cachedTrainingStats
    }

    private var programContext: ProgramStatsContext {
        guard let programId = student.programId else { return .empty }
        let peerStats = dataManager.sessionEvents
            .filter { $0.programId == programId }
            .flatMap { session in
                session.attendeeIds.compactMap { studentId -> TrainingSessionStats? in
                    let stats = TrainingSessionStats.calculate(for: studentId, from: dataManager.sessionEvents)
                    return stats.hasStats ? stats : nil
                }
            }
        return ProgramStatsContext.calculate(from: peerStats)
    }
    
    private var orgName: String {
        AuthManager.shared.currentOrganization?.name ?? "Basketball Academy"
    }

    private var shouldUseIpadLayout: Bool {
        #if os(iOS)
        return UIDevice.current.userInterfaceIdiom == .pad && horizontalSizeClass == .regular
        #else
        return false
        #endif
    }
    
    var body: some View {
        NavigationStack {
            ZStack {
                AppTheme.background.ignoresSafeArea()
                
                Group {
                    if shouldUseIpadLayout {
                        GeometryReader { geo in
                            let maxPreviewWidth = min(520.0, geo.size.width * 0.62)
                            let previewScale = max(0.95, min(1.15, maxPreviewWidth / 380.0))

                            HStack(spacing: 24) {
                                ScrollView {
                                    VStack(spacing: 16) {
                                        StudentParentReportView(
                                            student: student,
                                            player: player,
                                            contract: contract,
                                            programName: programName,
                                            coachName: coachName,
                                            orgName: orgName,
                                            trainingStats: trainingStats,
                                            programContext: programContext,
                                            profileImage: profileImage,
                                            isLightMode: isLightMode
                                        )
                                        .scaleEffect(previewScale)
                                        .frame(width: 380 * previewScale)
                                    }
                                    .frame(maxWidth: .infinity)
                                    .padding(.vertical, 24)
                                }
                                .frame(maxWidth: .infinity)

                                VStack(alignment: .leading, spacing: 16) {
                                    Button(action: { withAnimation { isLightMode.toggle() } }) {
                                        HStack(spacing: 8) {
                                            Image(systemName: isLightMode ? "sun.max.fill" : "moon.fill")
                                                .font(.system(size: 16))
                                            Text(isLightMode ? (loc.isChinese ? "浅色" : "Light") : (loc.isChinese ? "深色" : "Dark"))
                                                .font(.system(size: 14, weight: .semibold))
                                        }
                                        .foregroundColor(isLightMode ? .orange : .indigo)
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                        .padding(.horizontal, 14)
                                        .padding(.vertical, 12)
                                        .background(isLightMode ? Color.orange.opacity(0.15) : Color.indigo.opacity(0.15))
                                        .cornerRadius(14)
                                    }

                                    Button(action: shareReport) {
                                        HStack(spacing: 12) {
                                            if isGenerating {
                                                ProgressView()
                                                    .progressViewStyle(CircularProgressViewStyle(tint: .black))
                                            } else {
                                                Image(systemName: "square.and.arrow.up")
                                                    .font(.system(size: 18, weight: .semibold))
                                            }
                                            Text(loc.shareWithParent)
                                                .font(.system(size: 16, weight: .bold))
                                        }
                                        .foregroundColor(.black)
                                        .frame(maxWidth: .infinity)
                                        .padding(.vertical, 16)
                                        .background(AppTheme.accentGradient)
                                        .cornerRadius(16)
                                    }
                                    .disabled(isGenerating)

                                    Text(loc.autoGenerated)
                                        .font(.system(size: 12))
                                        .foregroundColor(AppTheme.textTertiary)
                                        .fixedSize(horizontal: false, vertical: true)

                                    Spacer(minLength: 0)
                                }
                                .frame(width: 320)
                                .padding(.vertical, 24)
                                .padding(.trailing, 20)
                            }
                            .padding(.leading, 20)
                        }
                    } else {
                        ScrollView {
                            VStack(spacing: 20) {
                                HStack {
                                    Spacer()
                                    Button(action: { withAnimation { isLightMode.toggle() } }) {
                                        HStack(spacing: 6) {
                                            Image(systemName: isLightMode ? "sun.max.fill" : "moon.fill")
                                                .font(.system(size: 14))
                                            Text(isLightMode ? (loc.isChinese ? "浅色" : "Light") : (loc.isChinese ? "深色" : "Dark"))
                                                .font(.system(size: 13, weight: .medium))
                                        }
                                        .foregroundColor(isLightMode ? .orange : .indigo)
                                        .padding(.horizontal, 12)
                                        .padding(.vertical, 6)
                                        .background(isLightMode ? Color.orange.opacity(0.15) : Color.indigo.opacity(0.15))
                                        .cornerRadius(8)
                                    }
                                }
                                .padding(.horizontal, 20)

                                GeometryReader { geo in
                                    let previewScale = min(1.0, (geo.size.width - 32) / 380)
                                    StudentParentReportView(
                                        student: student,
                                        player: player,
                                        contract: contract,
                                        programName: programName,
                                        coachName: coachName,
                                        orgName: orgName,
                                        trainingStats: trainingStats,
                                        programContext: programContext,
                                        profileImage: profileImage,
                                        isLightMode: isLightMode
                                    )
                                    .scaleEffect(previewScale, anchor: .top)
                                    .frame(width: geo.size.width, alignment: .center)
                                }
                                .frame(height: 720)

                                Button(action: shareReport) {
                                    HStack(spacing: 12) {
                                        if isGenerating {
                                            ProgressView()
                                                .progressViewStyle(CircularProgressViewStyle(tint: .black))
                                        } else {
                                            Image(systemName: "square.and.arrow.up")
                                                .font(.system(size: 18, weight: .semibold))
                                        }
                                        Text(loc.shareWithParent)
                                            .font(.system(size: 16, weight: .bold))
                                    }
                                    .foregroundColor(.black)
                                    .frame(maxWidth: .infinity)
                                    .padding(.vertical, 16)
                                    .background(AppTheme.accentGradient)
                                    .cornerRadius(16)
                                }
                                .disabled(isGenerating)
                                .padding(.horizontal, 20)

                                Text(loc.autoGenerated)
                                    .font(.system(size: 12))
                                    .foregroundColor(AppTheme.textTertiary)
                                    .multilineTextAlignment(.center)
                            }
                            .padding(.vertical, 20)
                        }
                    }
                }
            }
            .navigationTitle(loc.parentReport)
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(loc.close) { dismiss() }
                        .foregroundColor(AppTheme.textSecondary)
                }
            }
            #if os(iOS)
            .sheet(isPresented: $showShareSheet) {
                if let image = generatedImage {
                    ShareSheet(items: [image])
                }
            }
            #endif
            .onAppear {
                loadProfileImage()
                // Calculate training stats once on appear
                cachedTrainingStats = TrainingSessionStats.calculate(for: student.id, from: dataManager.sessionEvents)
            }
        }
    }
    
    private func loadProfileImage() {
        #if os(iOS)
        // Try to load from player's profileImageData first
        if let data = player?.profileImageData, let img = UIImage(data: data) {
            profileImage = img
            return
        }
        
        // Try to load from cache using student ID
        let cacheId = ImageCacheManager.studentImageId(student.id)
        if let cached = ImageCacheManager.shared.image(for: cacheId) {
            profileImage = cached
            return
        }
        
        // Try to load from URL
        if let urlString = student.profileImageUrl, !urlString.isEmpty {
            Task {
                let loaded = await ImageCacheManager.shared.loadImage(for: cacheId, from: urlString)
                await MainActor.run {
                    profileImage = loaded
                }
            }
        }
        #else
        // macOS: Try to load from player's profileImageData first
        if let data = player?.profileImageData, let img = NSImage(data: data) {
            profileImage = img
            return
        }
        #endif
    }
    
    private func shareReport() {
        #if os(iOS)
        isGenerating = true
        
        Task {
            if let image = await StudentReportImageGenerator.generateImage(
                student: student,
                player: player,
                contract: contract,
                programName: programName,
                coachName: coachName,
                orgName: orgName,
                trainingStats: trainingStats,
                programContext: programContext,
                profileImage: profileImage,
                isLightMode: isLightMode
            ) {
                generatedImage = image
                showShareSheet = true
            }
            isGenerating = false
        }
        #endif
    }
}

// MARK: - Share Sheet
#if os(iOS)
struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]
    
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    
    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
#endif
