import SwiftUI
import PhotosUI

// MARK: - Flighty-Styled Add Program View
/// A redesigned program creation form with Flighty's dark, confident aesthetic
struct FlightyAddProgramView: View {
    @EnvironmentObject var dataManager: DataManager
    @Environment(\.dismiss) var dismiss
    
    // Basic Info
    @State private var selectedProgramType: ProgramType = .group
    @State private var selectedAgeGroup: AgeGroup = .u12
    @State private var selectedMascot: ProgramMascot = .eagle
    @State private var durationWeeks = "12"
    @State private var description = ""
    @State private var difficultyLevel: Double = 5.0  // 1-10 scale
    
    // Coach Assignment
    @State private var selectedCoachId: UUID? = nil
    
    // Location
    @State private var selectedLocationId: UUID? = nil
    
    // Recurring schedule
    @State private var selectedDays: Set<Weekday> = [.monday]
    @State private var sessionTime = Calendar.current.date(bySettingHour: 18, minute: 0, second: 0, of: Date()) ?? Date()
    @State private var sessionDuration = 90
    
    // Objectives
    @State private var objectives: [String] = []
    @State private var newObjective = ""
    
    // Enrollment
    @State private var selectedStudentIds: Set<UUID> = []
    @State private var showingStudentPicker = false
    @State private var showingMascotPicker = false
    
    // Dates
    @State private var hasStartDate = false
    @State private var startDate = Date()
    
    // Stars/Tier Rating
    @State private var selectedStars: ProgramStars = .one
    
    var isValid: Bool {
        !selectedDays.isEmpty && selectedLocationId != nil
    }
    
    var autoGeneratedName: String {
        var parts: [String] = []
        
        // Day of the week (first selected day)
        if let firstDay = selectedDays.sorted(by: { $0.rawValue < $1.rawValue }).first {
            parts.append(firstDay.displayName)
        }
        
        // Time
        let formatter = DateFormatter()
        formatter.dateFormat = "h:mma"
        parts.append(formatter.string(from: sessionTime))
        
        // Location
        if let locationId = selectedLocationId,
           let location = dataManager.locations.first(where: { $0.id == locationId }) {
            parts.append(location.name)
        }
        
        return parts.joined(separator: " ")
    }
    
    var accentColor: Color {
        selectedMascot.color
    }
    
    var body: some View {
        NavigationStack {
            ScrollView(showsIndicators: false) {
                VStack(spacing: 0) {
                    // Hero header with mascot
                    heroHeader
                    
                    // Content sections
                    VStack(spacing: 20) {
                        // Auto-generated name preview
                        namePreviewSection
                        
                        // Program type selection
                        programTypeSection
                        
                        // Mascot selection
                        mascotSection
                        
                        // Age category
                        ageCategorySection
                        
                        // Duration
                        durationSection
                        
                        // Start date
                        startDateSection
                        
                        // Coach assignment
                        coachSection
                        
                        // Location
                        locationSection
                        
                        // Recurring days
                        recurringDaysSection
                        
                        // Session time
                        sessionTimeSection
                        
                        // Student enrollment
                        enrollmentSection
                        
                        // Objectives
                        objectivesSection
                        
                        // Description
                        descriptionSection
                        
                        // Difficulty level
                        difficultyLevelSection
                        
                        Spacer(minLength: 100)
                    }
                    .padding(20)
                }
            }
            .background(Color.black.ignoresSafeArea())
            .navigationBarTitleDisplayModeCompat(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                        .foregroundColor(.white.opacity(0.7))
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button(action: saveProgram) {
                        Text("CREATE")
                            .font(.system(size: 14, weight: .bold, design: .monospaced))
                            .foregroundColor(isValid ? .black : .white.opacity(0.3))
                            .padding(.horizontal, 16)
                            .padding(.vertical, 8)
                            .background(isValid ? accentColor : Color.white.opacity(0.1))
                            .cornerRadius(8)
                    }
                    .disabled(!isValid)
                }
            }
            .sheet(isPresented: $showingStudentPicker) {
                StudentPickerView(selectedIds: $selectedStudentIds, ageGroup: selectedAgeGroup)
            }
            .sheet(isPresented: $showingMascotPicker) {
                FlightyMascotSelectionView(selectedMascot: $selectedMascot)
            }
            .onChange(of: selectedAgeGroup) { _, newValue in
                objectives = newValue.defaultObjectives
                description = newValue.focusDescription
            }
            .onAppear {
                objectives = selectedAgeGroup.defaultObjectives
                description = selectedAgeGroup.focusDescription
            }
        }
    }
    
    // MARK: - Hero Header
    private var heroHeader: some View {
        VStack(spacing: 16) {
            // Mascot preview
            ZStack {
                Circle()
                    .fill(
                        LinearGradient(
                            colors: [accentColor, accentColor.opacity(0.6)],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .frame(width: 100, height: 100)
                
                Image(systemName: selectedMascot.icon)
                    .font(.system(size: 44, weight: .bold))
                    .foregroundColor(.white)
            }
            .shadow(color: accentColor.opacity(0.4), radius: 16, x: 0, y: 8)
            
            Text("NEW PROGRAM")
                .font(.system(size: 20, weight: .bold, design: .monospaced))
                .foregroundColor(.white)
            
            if !autoGeneratedName.isEmpty {
                Text(autoGeneratedName)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundColor(accentColor)
            } else {
                Text(selectedMascot.displayName)
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundColor(accentColor)
            }
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 32)
    }
    
    // MARK: - Name Preview Section
    private var namePreviewSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "PROGRAM NAME (AUTO-GENERATED)", icon: "text.badge.checkmark")
            
            HStack {
                Image(systemName: "sparkles")
                    .font(.system(size: 16))
                    .foregroundColor(accentColor)
                
                Text(autoGeneratedName.isEmpty ? "Select day, time & location" : autoGeneratedName)
                    .font(.system(size: 18, weight: .bold))
                    .foregroundColor(autoGeneratedName.isEmpty ? .white.opacity(0.3) : .white)
                
                Spacer()
            }
            .padding(16)
            .background(Color.white.opacity(0.05))
            .cornerRadius(12)
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(autoGeneratedName.isEmpty ? Color.white.opacity(0.1) : accentColor.opacity(0.5), lineWidth: 1)
            )
            
            Text("Name is automatically created from: Day + Time + Location")
                .font(.system(size: 11))
                .foregroundColor(.white.opacity(0.4))
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Program Type Section
    private var programTypeSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            sectionHeader(title: "PROGRAM TYPE", icon: "rectangle.3.group.fill")
            
            VStack(spacing: 10) {
                ForEach(ProgramType.allCases, id: \.self) { type in
                    Button(action: { selectedProgramType = type }) {
                        HStack(spacing: 12) {
                            Image(systemName: type.icon)
                                .font(.system(size: 18))
                                .foregroundColor(selectedProgramType == type ? accentColor : .white.opacity(0.5))
                                .frame(width: 32)
                            
                            VStack(alignment: .leading, spacing: 2) {
                                Text(type.displayName)
                                    .font(.system(size: 14, weight: .semibold))
                                    .foregroundColor(selectedProgramType == type ? .white : .white.opacity(0.7))
                                
                                Text(type.description)
                                    .font(.system(size: 11))
                                    .foregroundColor(.white.opacity(0.4))
                            }
                            
                            Spacer()
                            
                            if selectedProgramType == type {
                                Image(systemName: "checkmark.circle.fill")
                                    .font(.system(size: 20))
                                    .foregroundColor(accentColor)
                            }
                        }
                        .padding(14)
                        .background(selectedProgramType == type ? accentColor.opacity(0.1) : Color.white.opacity(0.03))
                        .cornerRadius(12)
                        .overlay(
                            RoundedRectangle(cornerRadius: 12)
                                .stroke(selectedProgramType == type ? accentColor : Color.white.opacity(0.1), lineWidth: selectedProgramType == type ? 2 : 1)
                        )
                    }
                }
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Mascot Section
    private var mascotSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            sectionHeader(title: "TEAM IDENTITY", icon: "star.fill")
            
            Button(action: { showingMascotPicker = true }) {
                HStack(spacing: 16) {
                    ZStack {
                        Circle()
                            .fill(accentColor.opacity(0.2))
                            .frame(width: 56, height: 56)
                        Image(systemName: selectedMascot.icon)
                            .font(.system(size: 24))
                            .foregroundColor(accentColor)
                    }
                    
                    VStack(alignment: .leading, spacing: 4) {
                        Text("MASCOT")
                            .font(.system(size: 10, weight: .bold, design: .monospaced))
                            .foregroundColor(.white.opacity(0.4))
                        Text(selectedMascot.displayName)
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundColor(.white)
                    }
                    
                    Spacer()
                    
                    Text("CHANGE")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(accentColor)
                    
                    Image(systemName: "chevron.right")
                        .font(.system(size: 12))
                        .foregroundColor(.white.opacity(0.3))
                }
                .padding(16)
                .background(Color.white.opacity(0.03))
                .cornerRadius(12)
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Duration Section
    private var durationSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "DURATION", icon: "calendar")
            
            HStack {
                TextField("12", text: $durationWeeks)
                    .keyboardTypeCompat(.numberPad)
                    .font(.system(size: 24, weight: .bold, design: .monospaced))
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                    .frame(width: 80)
                
                Text("WEEKS")
                    .font(.system(size: 14, weight: .medium, design: .monospaced))
                    .foregroundColor(.white.opacity(0.5))
                
                Spacer()
            }
            .padding(16)
            .background(Color.white.opacity(0.05))
            .cornerRadius(12)
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Start Date Section
    private var startDateSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "START DATE", icon: "calendar.badge.clock")
            
            DatePicker("", selection: $startDate, displayedComponents: .date)
                .datePickerStyle(.graphical)
                .labelsHidden()
                .colorScheme(.dark)
                .accentColor(accentColor)
                .padding(12)
                .background(Color.white.opacity(0.05))
                .cornerRadius(12)
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Age Category Section
    private var ageCategorySection: some View {
        VStack(alignment: .leading, spacing: 16) {
            sectionHeader(title: "AGE CATEGORY", icon: "person.2.fill")
            
            // Category chips
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 10) {
                    ForEach(AgeGroup.allCases, id: \.self) { group in
                        flightyCategoryChip(group)
                    }
                }
            }
            
            // Category info card
            categoryInfoCard
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    private func flightyCategoryChip(_ group: AgeGroup) -> some View {
        let isSelected = selectedAgeGroup == group
        let groupColor = Color(hex: group.colorHex)
        
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.2)) {
                selectedAgeGroup = group
            }
        }) {
            VStack(spacing: 4) {
                Text(group.rawValue)
                    .font(.system(size: 14, weight: .bold, design: .monospaced))
                Text(group.categoryName)
                    .font(.system(size: 9, weight: .medium))
                    .lineLimit(1)
            }
            .foregroundColor(isSelected ? .black : groupColor)
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(isSelected ? groupColor : groupColor.opacity(0.15))
            .cornerRadius(12)
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(isSelected ? groupColor : Color.clear, lineWidth: 2)
            )
        }
    }
    
    private var categoryInfoCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text(selectedAgeGroup.categoryName)
                        .font(.system(size: 16, weight: .bold))
                        .foregroundColor(Color(hex: selectedAgeGroup.colorHex))
                    Text(selectedAgeGroup.ageRange)
                        .font(.system(size: 12, design: .monospaced))
                        .foregroundColor(.white.opacity(0.5))
                }
                Spacer()
                Text(selectedAgeGroup.gradeEquivalent)
                    .font(.system(size: 11, weight: .bold, design: .monospaced))
                    .foregroundColor(Color(hex: selectedAgeGroup.colorHex))
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(Color(hex: selectedAgeGroup.colorHex).opacity(0.15))
                    .cornerRadius(8)
            }
            
            Rectangle()
                .fill(Color.white.opacity(0.1))
                .frame(height: 1)
            
            HStack(spacing: 24) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("BALL SIZE")
                        .font(.system(size: 9, weight: .bold, design: .monospaced))
                        .foregroundColor(.white.opacity(0.4))
                    Text(selectedAgeGroup.ballSizeDescription)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(.white)
                }
                
                Spacer()
                
                VStack(alignment: .trailing, spacing: 4) {
                    Text("RIM HEIGHT")
                        .font(.system(size: 9, weight: .bold, design: .monospaced))
                        .foregroundColor(.white.opacity(0.4))
                    Text(selectedAgeGroup.rimHeightDescription)
                        .font(.system(size: 13, weight: .medium))
                        .foregroundColor(.white)
                }
            }
        }
        .padding(16)
        .background(Color(hex: selectedAgeGroup.colorHex).opacity(0.08))
        .cornerRadius(12)
    }
    
    // MARK: - Location Section
    private var locationSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "LOCATION", icon: "mappin.circle.fill")
            
            if dataManager.locations.isEmpty {
                HStack {
                    Image(systemName: "mappin.slash")
                        .font(.system(size: 20))
                        .foregroundColor(.white.opacity(0.3))
                    
                    VStack(alignment: .leading, spacing: 2) {
                        Text("No locations in organization")
                            .font(.system(size: 14, weight: .medium))
                            .foregroundColor(.white.opacity(0.6))
                        Text("Add locations in Hub → Organization")
                            .font(.system(size: 12))
                            .foregroundColor(.white.opacity(0.4))
                    }
                    
                    Spacer()
                }
                .padding(16)
                .background(Color.white.opacity(0.03))
                .cornerRadius(12)
            } else {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 12) {
                        ForEach(dataManager.locations) { location in
                            locationButton(location)
                        }
                    }
                }
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    private func locationButton(_ location: Location) -> some View {
        let isSelected = selectedLocationId == location.id
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.2)) {
                selectedLocationId = location.id
            }
        }) {
            VStack(spacing: 8) {
                ZStack {
                    Circle()
                        .fill(isSelected ? accentColor : accentColor.opacity(0.3))
                        .frame(width: 50, height: 50)
                    Image(systemName: "mappin.circle.fill")
                        .font(.system(size: 20))
                        .foregroundColor(.white)
                }
                .overlay(
                    Circle()
                        .stroke(isSelected ? accentColor : Color.clear, lineWidth: 3)
                )
                
                Text(location.name)
                    .font(.system(size: 11, weight: .medium))
                    .foregroundColor(isSelected ? .white : .white.opacity(0.6))
                    .lineLimit(2)
                    .multilineTextAlignment(.center)
                    .frame(width: 80)
            }
        }
    }
    
    // MARK: - Recurring Days Section
    private var recurringDaysSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "RECURRING DAYS", icon: "calendar.badge.clock")
            
            Text("Select which days sessions will occur")
                .font(.system(size: 12))
                .foregroundColor(.white.opacity(0.5))
            
            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible()), GridItem(.flexible())], spacing: 10) {
                ForEach(Weekday.allCases, id: \.self) { day in
                    dayButton(day)
                }
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    private func dayButton(_ day: Weekday) -> some View {
        let isSelected = selectedDays.contains(day)
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.2)) {
                if isSelected {
                    selectedDays.remove(day)
                } else {
                    selectedDays.insert(day)
                }
            }
        }) {
            VStack(spacing: 4) {
                Text(day.shortName)
                    .font(.system(size: 12, weight: .bold))
                    .foregroundColor(isSelected ? .black : .white.opacity(0.6))
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, 12)
            .background(isSelected ? accentColor : Color.white.opacity(0.05))
            .cornerRadius(10)
            .overlay(
                RoundedRectangle(cornerRadius: 10)
                    .stroke(isSelected ? accentColor : Color.white.opacity(0.1), lineWidth: isSelected ? 2 : 1)
            )
        }
    }
    
    // MARK: - Session Time Section
    private var sessionTimeSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "SESSION TIME & DURATION", icon: "clock.fill")
            
            VStack(spacing: 12) {
                HStack {
                    Text("START TIME")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(.white.opacity(0.5))
                    
                    Spacer()
                    
                    DatePicker("", selection: $sessionTime, displayedComponents: .hourAndMinute)
                        .labelsHidden()
                        .colorScheme(.dark)
                        .accentColor(accentColor)
                }
                .padding(14)
                .background(Color.white.opacity(0.05))
                .cornerRadius(10)
                
                HStack {
                    Text("DURATION")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(.white.opacity(0.5))
                    
                    Spacer()
                    
                    Stepper("\(sessionDuration) min", value: $sessionDuration, in: 30...180, step: 15)
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(.white)
                }
                .padding(14)
                .background(Color.white.opacity(0.05))
                .cornerRadius(10)
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Description Section
    private var descriptionSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "DESCRIPTION", icon: "doc.text.fill")
            
            TextEditor(text: $description)
                .font(.system(size: 14))
                .foregroundColor(.white)
                .scrollContentBackground(.hidden)
                .frame(minHeight: 100)
                .padding(12)
                .background(Color.white.opacity(0.05))
                .cornerRadius(12)
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Difficulty Level Section
    private var difficultyLevelSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            sectionHeader(title: "DIFFICULTY LEVEL", icon: "chart.bar.fill")
            
            Text("Set the skill level for enrolled athletes (1 = Beginner, 10 = Elite)")
                .font(.system(size: 12))
                .foregroundColor(.white.opacity(0.5))
            
            VStack(spacing: 8) {
                HStack {
                    Text("LEVEL \(Int(difficultyLevel))")
                        .font(.system(size: 16, weight: .bold, design: .monospaced))
                        .foregroundColor(accentColor)
                    
                    Spacer()
                    
                    Text(difficultyLevelDescription)
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(.white.opacity(0.6))
                }
                
                Slider(value: $difficultyLevel, in: 1...10, step: 1)
                    .accentColor(accentColor)
                
                HStack {
                    Text("Beginner")
                        .font(.system(size: 10))
                        .foregroundColor(.white.opacity(0.4))
                    Spacer()
                    Text("Elite")
                        .font(.system(size: 10))
                        .foregroundColor(.white.opacity(0.4))
                }
            }
            .padding(16)
            .background(Color.white.opacity(0.05))
            .cornerRadius(12)
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    private var difficultyLevelDescription: String {
        switch Int(difficultyLevel) {
        case 1...2: return "Beginner - Learning basics"
        case 3...4: return "Novice - Building fundamentals"
        case 5...6: return "Intermediate - Developing skills"
        case 7...8: return "Advanced - Competitive level"
        case 9...10: return "Elite - High performance"
        default: return "Intermediate"
        }
    }
    
    // MARK: - Coach Section
    private var coachSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            sectionHeader(title: "ASSIGNED COACH", icon: "person.fill")
            
            if dataManager.staffCoaches.isEmpty {
                HStack {
                    Image(systemName: "person.badge.plus")
                        .font(.system(size: 20))
                        .foregroundColor(.white.opacity(0.3))
                    
                    VStack(alignment: .leading, spacing: 2) {
                        Text("No coaches in organization")
                            .font(.system(size: 14, weight: .medium))
                            .foregroundColor(.white.opacity(0.6))
                        Text("Add coaches in Hub → Organization")
                            .font(.system(size: 12))
                            .foregroundColor(.white.opacity(0.4))
                    }
                    
                    Spacer()
                }
                .padding(16)
                .background(Color.white.opacity(0.03))
                .cornerRadius(12)
            } else {
                // Coach selection
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 12) {
                        // None option
                        coachButton(nil, name: "None", initials: "—", color: .gray)
                        
                        ForEach(dataManager.staffCoaches.filter { $0.isActive }) { coach in
                            coachButton(coach.id, name: coach.name, initials: coach.initials, color: Color.avatarColor(coach.avatarColor), isYou: coach.id == dataManager.loggedInCoachId)
                        }
                    }
                }
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    private func coachButton(_ id: UUID?, name: String, initials: String, color: Color, isYou: Bool = false) -> some View {
        let isSelected = selectedCoachId == id
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.2)) {
                selectedCoachId = id
            }
        }) {
            VStack(spacing: 8) {
                ZStack {
                    Circle()
                        .fill(isSelected ? color : color.opacity(0.3))
                        .frame(width: 50, height: 50)
                    Text(initials)
                        .font(.system(size: 14, weight: .bold))
                        .foregroundColor(.white)
                }
                .overlay(
                    Circle()
                        .stroke(isSelected ? accentColor : Color.clear, lineWidth: 3)
                )
                
                VStack(spacing: 2) {
                    Text(name.split(separator: " ").first.map(String.init) ?? name)
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(isSelected ? .white : .white.opacity(0.6))
                        .lineLimit(1)
                    
                    if isYou {
                        Text("YOU")
                            .font(.system(size: 8, weight: .bold, design: .monospaced))
                            .foregroundColor(accentColor)
                    }
                }
            }
            .frame(width: 70)
        }
    }
    
    // MARK: - Objectives Section
    private var objectivesSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack {
                sectionHeader(title: "OBJECTIVES", icon: "target")
                Spacer()
                Button(action: { objectives = selectedAgeGroup.defaultObjectives }) {
                    Text("RESET")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(accentColor)
                }
            }
            
            // Objectives list
            VStack(spacing: 8) {
                ForEach(objectives, id: \.self) { objective in
                    HStack(spacing: 12) {
                        Image(systemName: "checkmark.circle.fill")
                            .font(.system(size: 16))
                            .foregroundColor(.green)
                        
                        Text(objective)
                            .font(.system(size: 14))
                            .foregroundColor(.white)
                            .lineLimit(2)
                        
                        Spacer()
                        
                        Button(action: { objectives.removeAll { $0 == objective } }) {
                            Image(systemName: "xmark")
                                .font(.system(size: 12))
                                .foregroundColor(.white.opacity(0.3))
                        }
                    }
                    .padding(12)
                    .background(Color.white.opacity(0.03))
                    .cornerRadius(10)
                }
            }
            
            // Add new objective
            HStack(spacing: 12) {
                TextField("", text: $newObjective, prompt: Text("Add objective...").foregroundColor(.white.opacity(0.3)))
                    .font(.system(size: 14))
                    .foregroundColor(.white)
                
                Button(action: addObjective) {
                    Image(systemName: "plus.circle.fill")
                        .font(.system(size: 24))
                        .foregroundColor(newObjective.isEmpty ? .white.opacity(0.2) : accentColor)
                }
                .disabled(newObjective.isEmpty)
            }
            .padding(14)
            .background(Color.white.opacity(0.05))
            .cornerRadius(12)
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Enrollment Section
    private var enrollmentSection: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack {
                sectionHeader(title: "ENROLLMENT", icon: "person.3.fill")
                Spacer()
                if !selectedStudentIds.isEmpty {
                    Text("\(selectedStudentIds.count)")
                        .font(.system(size: 12, weight: .bold, design: .monospaced))
                        .foregroundColor(.black)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(accentColor)
                        .cornerRadius(10)
                }
            }
            
            Button(action: { showingStudentPicker = true }) {
                HStack(spacing: 12) {
                    Image(systemName: "person.badge.plus")
                        .font(.system(size: 20))
                        .foregroundColor(accentColor)
                    
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Enroll Athletes")
                            .font(.system(size: 15, weight: .medium))
                            .foregroundColor(.white)
                        Text("\(selectedAgeGroup.rawValue) athletes shown by default")
                            .font(.system(size: 12))
                            .foregroundColor(.white.opacity(0.4))
                    }
                    
                    Spacer()
                    
                    Text("\(selectedStudentIds.count) SELECTED")
                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                        .foregroundColor(.white.opacity(0.5))
                    
                    Image(systemName: "chevron.right")
                        .font(.system(size: 12))
                        .foregroundColor(.white.opacity(0.3))
                }
                .padding(16)
                .background(Color.white.opacity(0.03))
                .cornerRadius(12)
            }
            
            // Enrolled preview
            if !selectedStudentIds.isEmpty {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: -8) {
                        ForEach(Array(selectedStudentIds.prefix(8)), id: \.self) { studentId in
                            if let student = dataManager.students.first(where: { $0.id == studentId }) {
                                StudentAvatarView(student: student, size: 40)
                                    .overlay(
                                        Circle()
                                            .stroke(Color(hex: "#1a1a2e"), lineWidth: 2)
                                    )
                            }
                        }
                        
                        if selectedStudentIds.count > 8 {
                            Circle()
                                .fill(accentColor)
                                .frame(width: 40, height: 40)
                                .overlay(
                                    Text("+\(selectedStudentIds.count - 8)")
                                        .font(.system(size: 12, weight: .bold))
                                        .foregroundColor(.white)
                                )
                                .overlay(
                                    Circle()
                                        .stroke(Color(hex: "#1a1a2e"), lineWidth: 2)
                                )
                        }
                    }
                }
            }
        }
        .padding(20)
        .background(Color(hex: "#1a1a2e"))
        .cornerRadius(16)
    }
    
    // MARK: - Helpers
    private func sectionHeader(title: String, icon: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: icon)
                .font(.system(size: 11))
                .foregroundColor(.white.opacity(0.4))
            Text(title)
                .font(.system(size: 12, weight: .bold, design: .monospaced))
                .foregroundColor(.white.opacity(0.6))
        }
    }
    
    private func addObjective() {
        guard !newObjective.isEmpty else { return }
        objectives.append(newObjective)
        newObjective = ""
    }
    
    private func saveProgram() {
        let weeks = Int(durationWeeks) ?? 12
        let endDate = Calendar.current.date(byAdding: .weekOfYear, value: weeks, to: startDate)
        
        // Get location name
        let locationName = selectedLocationId != nil ? dataManager.locations.first(where: { $0.id == selectedLocationId })?.name : nil
        
        let program = Program(
            name: autoGeneratedName,
            programType: selectedProgramType,
            ageGroup: selectedAgeGroup,
            durationWeeks: weeks,
            description: description.isEmpty ? nil : description,
            objectives: objectives,
            enrolledStudentIds: Array(selectedStudentIds),
            coachId: selectedCoachId,
            createdByCoachId: selectedCoachId ?? dataManager.loggedInCoachId ?? AuthManager.shared.currentUser?.id,
            status: .active,
            mascot: selectedMascot,
            startDate: startDate,
            endDate: endDate,
            stars: .one,
            recurringDays: Array(selectedDays),
            defaultSessionTime: sessionTime,
            defaultSessionDurationMinutes: sessionDuration,
            locationId: selectedLocationId,
            locationName: locationName
        )
        
        dataManager.addProgram(program)
        dismiss()
    }
}

// MARK: - Flighty Mascot Selection View
struct FlightyMascotSelectionView: View {
    @Environment(\.dismiss) var dismiss
    @Binding var selectedMascot: ProgramMascot
    
    private let columns = [
        GridItem(.flexible()),
        GridItem(.flexible()),
        GridItem(.flexible())
    ]
    
    var body: some View {
        NavigationStack {
            ScrollView(showsIndicators: false) {
                LazyVGrid(columns: columns, spacing: 16) {
                    ForEach(ProgramMascot.allCases, id: \.self) { mascot in
                        flightyMascotCard(mascot)
                    }
                }
                .padding(20)
            }
            .background(Color.black.ignoresSafeArea())
            .navigationBarTitleDisplayModeCompat(.inline)
            .toolbar {
                ToolbarItem(placement: .principal) {
                    Text("CHOOSE MASCOT")
                        .font(.system(size: 14, weight: .bold, design: .monospaced))
                        .foregroundColor(.white)
                }
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                        .foregroundColor(.white.opacity(0.7))
                }
            }
        }
    }
    
    private func flightyMascotCard(_ mascot: ProgramMascot) -> some View {
        let isSelected = selectedMascot == mascot
        return Button(action: {
            selectedMascot = mascot
            dismiss()
        }) {
            VStack(spacing: 10) {
                ZStack {
                    Circle()
                        .fill(
                            LinearGradient(
                                colors: [mascot.color, mascot.color.opacity(0.6)],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            )
                        )
                        .frame(width: 60, height: 60)
                    
                    Image(systemName: mascot.icon)
                        .font(.system(size: 26, weight: .bold))
                        .foregroundColor(.white)
                }
                .overlay(
                    Circle()
                        .stroke(isSelected ? Color.white : Color.clear, lineWidth: 3)
                )
                .shadow(color: mascot.color.opacity(isSelected ? 0.5 : 0.2), radius: isSelected ? 10 : 4, x: 0, y: 4)
                
                Text(mascot.displayName)
                    .font(.system(size: 12, weight: .semibold))
                    .foregroundColor(isSelected ? mascot.color : .white.opacity(0.7))
                    .lineLimit(1)
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, 16)
            .background(
                RoundedRectangle(cornerRadius: 16)
                    .fill(isSelected ? mascot.color.opacity(0.15) : Color(hex: "#1a1a2e"))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 16)
                    .stroke(isSelected ? mascot.color : Color.white.opacity(0.1), lineWidth: isSelected ? 2 : 1)
            )
        }
    }
}

// MARK: - Preview
#Preview {
    FlightyAddProgramView()
        .environmentObject(DataManager.shared)
}
