import SwiftUI

// MARK: - Streamlined Add Program View
/// A clean, simplified program creation flow with optional phases
struct StreamlinedAddProgramView: View {
    @EnvironmentObject var dataManager: DataManager
    @Environment(\.dismiss) var dismiss
    
    // Core settings
    @State private var selectedMascot: ProgramMascot = .eagle
    @State private var selectedAgeGroup: AgeGroup = .u12
    @State private var selectedLocationId: UUID? = nil
    @State private var selectedCoachId: UUID? = nil
    
    // Schedule
    @State private var startDate = Date()
    @State private var durationWeeks = 2
    @State private var sessionTime = Calendar.current.date(bySettingHour: 18, minute: 0, second: 0, of: Date()) ?? Date()
    @State private var sessionDuration = 90
    
    // Phases toggle
    @State private var usesPhases = false
    
    // Recurring schedule with themes (for phase-less programs)
    @State private var weeklySchedule: [WeekdaySession] = []
    
    // Athletes
    @State private var selectedStudentIds: Set<UUID> = []
    @State private var showingStudentPicker = false
    
    // Sheets
    @State private var showingMascotPicker = false
    
    private let isChinese = LocalizationManager.shared.currentLanguage == .chinese
    
    var isValid: Bool {
        selectedLocationId != nil && !weeklySchedule.isEmpty
    }
    
    var autoGeneratedName: String {
        var parts: [String] = []
        if let firstSession = weeklySchedule.sorted(by: { $0.weekday.rawValue < $1.weekday.rawValue }).first {
            parts.append(firstSession.weekday.displayName)
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "h:mma"
        parts.append(formatter.string(from: sessionTime))
        if let locationId = selectedLocationId,
           let location = dataManager.locations.first(where: { $0.id == locationId }) {
            parts.append(location.name)
        }
        return parts.joined(separator: " ")
    }
    
    var accentColor: Color { selectedMascot.color }
    
    var body: some View {
        NavigationStack {
            ScrollView(showsIndicators: false) {
                VStack(spacing: 12) {
                    // Compact inline header
                    compactHeader
                    
                    // Essential setup - tighter layout
                    essentialsCard
                    
                    // Schedule - combined and compact
                    scheduleCard
                    
                    // Phases toggle - inline
                    phasesToggleCard
                    
                    // Weekly schedule with themes (only if no phases)
                    if !usesPhases {
                        weeklyScheduleCard
                    }
                    
                    // Athletes enrollment
                    athletesCard
                    
                    Spacer(minLength: 80)
                }
                .padding(.horizontal, 16)
                .padding(.top, 8)
            }
            .background(AppTheme.background.ignoresSafeArea())
            .navigationBarTitleDisplayModeCompat(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(isChinese ? "取消" : "Cancel") { dismiss() }
                        .foregroundColor(AppTheme.textSecondary)
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button(action: createProgram) {
                        Text(isChinese ? "创建" : "CREATE")
                            .font(.system(size: 14, weight: .bold, design: .monospaced))
                            .foregroundColor(isValid ? .white : AppTheme.textTertiary)
                            .padding(.horizontal, 16)
                            .padding(.vertical, 8)
                            .background(isValid ? accentColor : AppTheme.surfaceColor)
                            .cornerRadius(8)
                    }
                    .disabled(!isValid)
                }
            }
            .sheet(isPresented: $showingMascotPicker) {
                FlightyMascotSelectionView(selectedMascot: $selectedMascot)
            }
            .sheet(isPresented: $showingStudentPicker) {
                StudentMultiPickerView(
                    selectedIds: $selectedStudentIds,
                    students: dataManager.students,
                    accentColor: accentColor
                )
            }
        }
    }
    
    // MARK: - Compact Header
    private var compactHeader: some View {
        HStack(spacing: 12) {
            // Mascot button - smaller
            Button(action: { showingMascotPicker = true }) {
                ZStack {
                    Circle()
                        .fill(accentColor.opacity(0.15))
                        .frame(width: 48, height: 48)
                    Image(systemName: selectedMascot.icon)
                        .font(.system(size: 20, weight: .bold))
                        .foregroundColor(accentColor)
                }
            }
            
            VStack(alignment: .leading, spacing: 2) {
                Text(isChinese ? "新项目" : "NEW PROGRAM")
                    .font(.system(size: 10, weight: .bold, design: .monospaced))
                    .foregroundColor(AppTheme.textTertiary)
                
                Text(autoGeneratedName.isEmpty ? selectedMascot.displayName : autoGeneratedName)
                    .font(.system(size: 15, weight: .bold))
                    .foregroundColor(AppTheme.textPrimary)
                    .lineLimit(1)
            }
            
            Spacer()
            
            // Time preview
            VStack(alignment: .trailing, spacing: 2) {
                Text(sessionTime, style: .time)
                    .font(.system(size: 18, weight: .bold, design: .monospaced))
                    .foregroundColor(AppTheme.textPrimary)
                Text("\(sessionDuration)min")
                    .font(.system(size: 11))
                    .foregroundColor(AppTheme.textTertiary)
            }
        }
        .padding(12)
        .background(AppTheme.cardBackground)
        .cornerRadius(12)
    }
    
    // MARK: - Essentials Card
    private var essentialsCard: some View {
        VStack(alignment: .leading, spacing: 10) {
            // Age Group - compact inline label
            HStack(spacing: 6) {
                Text(isChinese ? "年龄" : "AGE")
                    .font(.system(size: 10, weight: .bold, design: .monospaced))
                    .foregroundColor(AppTheme.textTertiary)
                    .frame(width: 36, alignment: .leading)
                
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 6) {
                        ForEach(AgeGroup.allCases, id: \.self) { group in
                            ageChip(group)
                        }
                    }
                }
            }
            
            // Location - compact
            HStack(spacing: 6) {
                Text(isChinese ? "场地" : "LOC")
                    .font(.system(size: 10, weight: .bold, design: .monospaced))
                    .foregroundColor(AppTheme.textTertiary)
                    .frame(width: 36, alignment: .leading)
                
                if dataManager.locations.isEmpty {
                    Text(isChinese ? "请先添加场地" : "Add locations first")
                        .font(.system(size: 12))
                        .foregroundColor(AppTheme.textTertiary)
                } else {
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 6) {
                            ForEach(dataManager.locations) { location in
                                locationChip(location)
                            }
                        }
                    }
                }
            }
            
            // Coach - compact
            if !dataManager.staffCoaches.isEmpty {
                HStack(spacing: 6) {
                    Text(isChinese ? "教练" : "COACH")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textTertiary)
                        .frame(width: 36, alignment: .leading)
                    
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 6) {
                            coachChip(nil, name: isChinese ? "无" : "None")
                            ForEach(dataManager.staffCoaches.filter { $0.isActive }) { coach in
                                coachChip(coach.id, name: coach.name, initials: coach.initials, color: Color.avatarColor(coach.avatarColor))
                            }
                        }
                    }
                }
            }
        }
        .padding(12)
        .background(AppTheme.cardBackground)
        .cornerRadius(12)
    }
    
    // MARK: - Schedule Card
    private var scheduleCard: some View {
        VStack(spacing: 8) {
            // Row 1: Start date + Weeks
            HStack(spacing: 8) {
                // Start Date - compact
                HStack(spacing: 8) {
                    Text(isChinese ? "开始" : "START")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textTertiary)
                    DatePicker("", selection: $startDate, displayedComponents: .date)
                        .datePickerStyle(.compact)
                        .labelsHidden()
                        .accentColor(accentColor)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 8)
                .background(AppTheme.surfaceColor)
                .cornerRadius(8)
                
                // Weeks - compact stepper
                HStack(spacing: 6) {
                    Text(isChinese ? "周数" : "WKS")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textTertiary)
                    
                    Text("\(durationWeeks)")
                        .font(.system(size: 16, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textPrimary)
                        .frame(width: 28)
                    
                    VStack(spacing: 0) {
                        Button(action: { if durationWeeks < 52 { durationWeeks += 1 } }) {
                            Image(systemName: "plus")
                                .font(.system(size: 11, weight: .bold))
                                .foregroundColor(AppTheme.textSecondary)
                                .frame(width: 28, height: 22)
                        }
                        Divider()
                        Button(action: { if durationWeeks > 1 { durationWeeks -= 1 } }) {
                            Image(systemName: "minus")
                                .font(.system(size: 11, weight: .bold))
                                .foregroundColor(AppTheme.textSecondary)
                                .frame(width: 28, height: 22)
                        }
                    }
                    .background(AppTheme.surfaceColor.opacity(0.5))
                    .cornerRadius(6)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background(AppTheme.surfaceColor)
                .cornerRadius(8)
            }
            
            // Row 2: Time + Duration
            HStack(spacing: 8) {
                // Time
                HStack(spacing: 8) {
                    Text(isChinese ? "时间" : "TIME")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textTertiary)
                    DatePicker("", selection: $sessionTime, displayedComponents: .hourAndMinute)
                        .datePickerStyle(.compact)
                        .labelsHidden()
                        .accentColor(accentColor)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 8)
                .background(AppTheme.surfaceColor)
                .cornerRadius(8)
                
                // Duration - compact
                HStack(spacing: 6) {
                    Text(isChinese ? "时长" : "DUR")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textTertiary)
                    
                    Text("\(sessionDuration)")
                        .font(.system(size: 14, weight: .bold, design: .monospaced))
                        .foregroundColor(AppTheme.textPrimary)
                    Text("min")
                        .font(.system(size: 10))
                        .foregroundColor(AppTheme.textTertiary)
                    
                    VStack(spacing: 0) {
                        Button(action: { if sessionDuration < 180 { sessionDuration += 15 } }) {
                            Image(systemName: "plus")
                                .font(.system(size: 11, weight: .bold))
                                .foregroundColor(AppTheme.textSecondary)
                                .frame(width: 28, height: 22)
                        }
                        Divider()
                        Button(action: { if sessionDuration > 30 { sessionDuration -= 15 } }) {
                            Image(systemName: "minus")
                                .font(.system(size: 11, weight: .bold))
                                .foregroundColor(AppTheme.textSecondary)
                                .frame(width: 28, height: 22)
                        }
                    }
                    .background(AppTheme.surfaceColor.opacity(0.5))
                    .cornerRadius(6)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background(AppTheme.surfaceColor)
                .cornerRadius(8)
            }
        }
        .padding(12)
        .background(AppTheme.cardBackground)
        .cornerRadius(12)
    }
    
    // MARK: - Phases Toggle Card
    private var phasesToggleCard: some View {
        Toggle(isOn: $usesPhases) {
            HStack(spacing: 10) {
                Image(systemName: usesPhases ? "square.stack.3d.up.fill" : "calendar.day.timeline.left")
                    .font(.system(size: 16))
                    .foregroundColor(accentColor)
                    .frame(width: 24)
                
                VStack(alignment: .leading, spacing: 1) {
                    Text(isChinese ? "使用训练阶段" : "Use Training Phases")
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(AppTheme.textPrimary)
                    Text(isChinese ? "直接安排每日训练主题" : "Set daily themes directly")
                        .font(.system(size: 11))
                        .foregroundColor(AppTheme.textTertiary)
                }
            }
        }
        .toggleStyle(SwitchToggleStyle(tint: accentColor))
        .padding(12)
        .background(AppTheme.cardBackground)
        .cornerRadius(12)
    }
    
    // MARK: - Athletes Card
    private var athletesCard: some View {
        Button(action: { showingStudentPicker = true }) {
            HStack(spacing: 10) {
                Image(systemName: "person.3.fill")
                    .font(.system(size: 14))
                    .foregroundColor(accentColor)
                    .frame(width: 24)
                
                if selectedStudentIds.isEmpty {
                    Text(isChinese ? "添加学员（可选）" : "Add Athletes (optional)")
                        .font(.system(size: 14, weight: .medium))
                        .foregroundColor(AppTheme.textSecondary)
                } else {
                    // Show selected athletes preview
                    let selectedStudents = dataManager.students.filter { selectedStudentIds.contains($0.id) }
                    HStack(spacing: -6) {
                        ForEach(selectedStudents.prefix(4)) { student in
                            Circle()
                                .fill(Color.avatarColor(student.avatarColor))
                                .frame(width: 26, height: 26)
                                .overlay(
                                    Text(student.initials)
                                        .font(.system(size: 9, weight: .bold))
                                        .foregroundColor(.white)
                                )
                                .overlay(
                                    Circle()
                                        .stroke(AppTheme.cardBackground, lineWidth: 2)
                                )
                        }
                        if selectedStudents.count > 4 {
                            Circle()
                                .fill(accentColor.opacity(0.2))
                                .frame(width: 26, height: 26)
                                .overlay(
                                    Text("+\(selectedStudents.count - 4)")
                                        .font(.system(size: 9, weight: .bold))
                                        .foregroundColor(accentColor)
                                )
                        }
                    }
                    
                    Text("\(selectedStudentIds.count) " + (isChinese ? "名学员" : "athletes"))
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(AppTheme.textSecondary)
                }
                
                Spacer()
                
                Image(systemName: "chevron.right")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundColor(AppTheme.textTertiary)
            }
            .padding(12)
            .background(AppTheme.cardBackground)
            .cornerRadius(12)
        }
    }
    
    // MARK: - Weekly Schedule Card (for phase-less programs)
    private var weeklyScheduleCard: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Text(isChinese ? "训练日" : "TRAINING DAYS")
                    .font(.system(size: 10, weight: .bold, design: .monospaced))
                    .foregroundColor(AppTheme.textTertiary)
                Spacer()
                if weeklySchedule.count > 0 {
                    Text("\(weeklySchedule.count)")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(accentColor)
                        .padding(.horizontal, 8)
                        .padding(.vertical, 3)
                        .background(accentColor.opacity(0.15))
                        .cornerRadius(6)
                }
            }
            
            // Compact day grid - 2 rows
            VStack(spacing: 6) {
                HStack(spacing: 6) {
                    ForEach(Weekday.allCases.prefix(4), id: \.self) { day in
                        compactDayChip(day)
                    }
                }
                HStack(spacing: 6) {
                    ForEach(Weekday.allCases.suffix(3), id: \.self) { day in
                        compactDayChip(day)
                    }
                    Spacer()
                }
            }
            
            // Show focus pickers for selected days
            if !weeklySchedule.isEmpty {
                VStack(spacing: 6) {
                    ForEach(weeklySchedule.sorted { $0.weekday.rawValue < $1.weekday.rawValue }, id: \.weekday) { session in
                        compactFocusRow(for: session.weekday)
                    }
                }
            }
        }
        .padding(12)
        .background(AppTheme.cardBackground)
        .cornerRadius(12)
    }
    
    private func compactDayChip(_ day: Weekday) -> some View {
        let isSelected = weeklySchedule.contains { $0.weekday == day }
        
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.15)) {
                if isSelected {
                    weeklySchedule.removeAll { $0.weekday == day }
                } else {
                    weeklySchedule.append(WeekdaySession(weekday: day, focus: []))
                }
            }
        }) {
            Text(day.shortName)
                .font(.system(size: 12, weight: .semibold))
                .foregroundColor(isSelected ? .white : AppTheme.textSecondary)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 10)
                .background(isSelected ? accentColor : AppTheme.surfaceColor)
                .cornerRadius(8)
        }
    }
    
    private func compactFocusRow(for day: Weekday) -> some View {
        let binding = Binding<[TrainingFocus]>(
            get: { weeklySchedule.first { $0.weekday == day }?.focus ?? [] },
            set: { newValue in
                if let index = weeklySchedule.firstIndex(where: { $0.weekday == day }) {
                    weeklySchedule[index].focus = newValue
                }
            }
        )
        
        return HStack(spacing: 8) {
            Text(day.shortName)
                .font(.system(size: 10, weight: .bold, design: .monospaced))
                .foregroundColor(accentColor)
                .frame(width: 32)
            
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 4) {
                    ForEach(TrainingFocus.allCases, id: \.self) { focus in
                        let isSelected = binding.wrappedValue.contains(focus)
                        Button(action: {
                            withAnimation(.easeInOut(duration: 0.1)) {
                                if isSelected {
                                    binding.wrappedValue.removeAll { $0 == focus }
                                } else {
                                    binding.wrappedValue.append(focus)
                                }
                            }
                        }) {
                            Text(focus.displayName)
                                .font(.system(size: 10, weight: .medium))
                                .foregroundColor(isSelected ? .white : AppTheme.textTertiary)
                                .padding(.horizontal, 8)
                                .padding(.vertical, 4)
                                .background(isSelected ? accentColor.opacity(0.8) : AppTheme.surfaceColor)
                                .cornerRadius(10)
                        }
                    }
                }
            }
        }
        .padding(.vertical, 6)
        .padding(.horizontal, 8)
        .background(accentColor.opacity(0.06))
        .cornerRadius(8)
    }
    
    // MARK: - Chip Views
    private func ageChip(_ group: AgeGroup) -> some View {
        let isSelected = selectedAgeGroup == group
        let groupColor = Color(hex: group.colorHex)
        
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.15)) {
                selectedAgeGroup = group
            }
        }) {
            Text(group.rawValue)
                .font(.system(size: 12, weight: .bold, design: .monospaced))
                .foregroundColor(isSelected ? .white : groupColor)
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background(isSelected ? groupColor : groupColor.opacity(0.12))
                .cornerRadius(12)
        }
    }
    
    private func locationChip(_ location: Location) -> some View {
        let isSelected = selectedLocationId == location.id
        
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.15)) {
                selectedLocationId = location.id
            }
        }) {
            HStack(spacing: 4) {
                Image(systemName: "mappin")
                    .font(.system(size: 9))
                Text(location.name)
                    .font(.system(size: 12, weight: .medium))
            }
            .foregroundColor(isSelected ? .white : AppTheme.textSecondary)
            .padding(.horizontal, 10)
            .padding(.vertical, 6)
            .background(isSelected ? accentColor : AppTheme.surfaceColor)
            .cornerRadius(12)
        }
    }
    
    private func coachChip(_ id: UUID?, name: String, initials: String = "—", color: Color = .gray) -> some View {
        let isSelected = selectedCoachId == id
        
        return Button(action: {
            withAnimation(.easeInOut(duration: 0.15)) {
                selectedCoachId = id
            }
        }) {
            HStack(spacing: 4) {
                Circle()
                    .fill(color.opacity(isSelected ? 1 : 0.5))
                    .frame(width: 18, height: 18)
                    .overlay(
                        Text(initials.prefix(2))
                            .font(.system(size: 8, weight: .bold))
                            .foregroundColor(.white)
                    )
                Text(name.split(separator: " ").first.map(String.init) ?? name)
                    .font(.system(size: 12, weight: .medium))
            }
            .foregroundColor(isSelected ? .white : AppTheme.textSecondary)
            .padding(.horizontal, 8)
            .padding(.vertical, 5)
            .background(isSelected ? accentColor : AppTheme.surfaceColor)
            .cornerRadius(12)
        }
    }
    
    // MARK: - Helpers
    private func sectionHeader(_ title: String, icon: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: icon)
                .font(.system(size: 11))
                .foregroundColor(AppTheme.textTertiary)
            Text(title)
                .font(.system(size: 11, weight: .bold, design: .monospaced))
                .foregroundColor(AppTheme.textSecondary)
        }
    }
    
    // MARK: - Create Program
    private func createProgram() {
        let endDate = Calendar.current.date(byAdding: .weekOfYear, value: durationWeeks, to: startDate)
        let locationName = selectedLocationId != nil ? dataManager.locations.first(where: { $0.id == selectedLocationId })?.name : nil
        
        let program = Program(
            name: autoGeneratedName,
            programType: .group,
            ageGroup: selectedAgeGroup,
            durationWeeks: durationWeeks,
            enrolledStudentIds: Array(selectedStudentIds),
            coachId: selectedCoachId,
            createdByCoachId: dataManager.loggedInCoachId,
            status: .active,
            mascot: selectedMascot,
            startDate: startDate,
            endDate: endDate,
            recurringDays: weeklySchedule.map { $0.weekday },
            defaultSessionTime: sessionTime,
            defaultSessionDurationMinutes: sessionDuration,
            locationId: selectedLocationId,
            locationName: locationName,
            usesPhases: usesPhases
        )
        
        dataManager.addProgram(program)
        
        // If not using phases, create recurring sessions
        if !usesPhases {
            createRecurringSessions(for: program)
        }
        
        dismiss()
    }
    
    private func createRecurringSessions(for program: Program) {
        let calendar = Calendar.current
        var currentDate = startDate
        let endDate = calendar.date(byAdding: .weekOfYear, value: durationWeeks, to: startDate) ?? startDate
        
        // Get time components from sessionTime
        let timeComponents = calendar.dateComponents([.hour, .minute], from: sessionTime)
        
        while currentDate <= endDate {
            let weekday = calendar.component(.weekday, from: currentDate)
            
            // Check if this day is in our schedule
            if let session = weeklySchedule.first(where: { $0.weekday.rawValue == weekday }) {
                // Create session for this day
                let sessionStartTime = calendar.date(bySettingHour: timeComponents.hour ?? 18,
                                                      minute: timeComponents.minute ?? 0,
                                                      second: 0, of: currentDate) ?? currentDate
                let sessionEndTime = calendar.date(byAdding: .minute, value: sessionDuration, to: sessionStartTime) ?? sessionStartTime
                
                // Generate title from focus
                let focusTitle = session.focus.isEmpty 
                    ? (isChinese ? "训练" : "Training")
                    : session.focus.map { $0.displayName }.joined(separator: " & ")
                
                let sessionEvent = SessionEvent(
                    programId: program.id,
                    sessionType: .training,
                    title: focusTitle,
                    date: currentDate,
                    startTime: sessionStartTime,
                    endTime: sessionEndTime,
                    location: program.locationName,
                    developmentFocus: session.focus,
                    createdByCoachId: dataManager.loggedInCoachId
                )
                
                dataManager.addSessionEvent(sessionEvent)
            }
            
            // Move to next day
            currentDate = calendar.date(byAdding: .day, value: 1, to: currentDate) ?? currentDate
        }
    }
}

// MARK: - Weekday Session Model
struct WeekdaySession: Identifiable {
    let id = UUID()
    var weekday: Weekday
    var focus: [TrainingFocus]
}

// MARK: - Preview
#Preview {
    StreamlinedAddProgramView()
        .environmentObject(DataManager.shared)
}
